/* Generated by scripts/build-content.py — listing fields only.
 * Source of truth: js/articles-data.js
 * Do not edit by hand.
 */
(function (global) {
  'use strict';
  var BY_SLUG = {
  "ai-ux-guardrails": {
    "slug": "ai-ux-guardrails",
    "tag": "هوش مصنوعی",
    "tagFilter": "ai",
    "title": "گاردریل تجربه کاربری برای قابلیت‌های هوش مصنوعی در محصول",
    "date": "۲ آذر ۱۴۰۴",
    "read": "۷ دقیقه",
    "hero": "assets/images/article/ai-ux-guardrails-hero.webp",
    "lead": "وقتی مدل اشتباه می‌کند، UI باید اعتماد را نگه دارد. گاردریل UX یعنی شفافیت محدودیت، کنترل ویرایش، مسیر لغو و نمایش منبع — نه جعبهٔ جادویی بی‌مسئولیت."
  },
  "content-seo-funnel": {
    "slug": "content-seo-funnel",
    "tag": "مارکتینگ",
    "tagFilter": "marketing",
    "title": "محتوای تخصصی چگونه قیف جذب محصول B2B را گرم می‌کند؟",
    "date": "۱۵ آبان ۱۴۰۴",
    "read": "۵ دقیقه",
    "hero": "assets/images/article/content-seo-funnel-hero.webp",
    "lead": "وبلاگ B2B ویترین مقاله نیست؛ موتور گرم‌کردن قیف برای خریدار فنی و تصمیم‌گیر است. محتوای تخصصی وقتی کار می‌کند که به مرحلهٔ سفر و CTA درست وصل باشد."
  },
  "design-eng-sync": {
    "slug": "design-eng-sync",
    "tag": "استارتاپ",
    "tagFilter": "startup",
    "title": "مدیریت چابک تیم‌های توزیع‌شده: هماهنگی کامل دیزاین و مهندسی در پروژه‌ها",
    "date": "۲۸ بهمن ۱۴۰۴",
    "read": "۶ دقیقه",
    "hero": "assets/images/article/design-eng-sync-hero.webp",
    "lead": "در تیم‌های توزیع‌شده، فاصلهٔ دیزاین و مهندسی با فایل Figma زیبا پر نمی‌شود. نیاز به منبع حقیقت، تعریف Ready و بازبینی مشترک است تا سرعت بدون آشفتگی بماند."
  },
  "design-system-scale": {
    "slug": "design-system-scale",
    "tag": "UI/UX",
    "tagFilter": "uiux",
    "title": "سیستم طراحی وقتی تیم بزرگ می‌شود: از توکن تا مسئولیت کامپوننت",
    "date": "۲۲ دی ۱۴۰۴",
    "read": "۸ دقیقه",
    "hero": "assets/images/article/design-system-scale-hero.webp",
    "lead": "وقتی تیم بزرگ می‌شود، سلیقهٔ فردی سیستم را می‌شکند. توکن، مالکیت کامپوننت، مستند و نسخهٔ انتشار جلوی بدهی بصری و ناهماهنگی فرانت را می‌گیرند."
  },
  "digital-product-guide": {
    "slug": "digital-product-guide",
    "tag": "طراحی محصول",
    "tagFilter": "product",
    "title": "چگونه یک محصول دیجیتال موفق بسازیم: راهنمای جامع استودیو هش",
    "date": "۱۲ مرداد ۱۴۰۳",
    "read": "۸ دقیقه",
    "hero": "assets/images/article/digital-product-guide-hero.webp",
    "lead": "محصول دیجیتال موفق انباشت فیچر نیست؛ زنجیره‌ای از تعریف مسئله، اعتبارسنجی فرضیه، طراحی تجربه و تحویل مهندسی است. در استودیو هش دیزاین و کد را در خدمت یک هدف می‌گذاریم: کوتاه‌کردن مسیر کاربر تا ارزش واقعی."
  },
  "edge-caching": {
    "slug": "edge-caching",
    "tag": "توسعه",
    "tagFilter": "dev",
    "title": "کش لبه و رندر ترکیبی: سرعت واقعی برای کاربر ایرانی",
    "date": "۱۸ آذر ۱۴۰۴",
    "read": "۹ دقیقه",
    "hero": "assets/images/article/edge-caching-hero.webp",
    "lead": "برای کاربر ایرانی تأخیر شبکه بخشی از مسئله است. کش لبه، ISR و جداسازی محتوای عمومی از خصوصی تفاوت محسوس در TTFB و پایداری می‌سازد."
  },
  "enterprise-ai": {
    "slug": "enterprise-ai",
    "tag": "هوش مصنوعی",
    "tagFilter": "ai",
    "title": "یکپارچه‌سازی ابزارهای هوش مصنوعی و مدل‌های زبانی در سیستم‌های سازمانی",
    "date": "۱۲ اسفند ۱۴۰۴",
    "read": "۹ دقیقه",
    "hero": "assets/images/article/enterprise-ai-hero.webp",
    "lead": "LLM سازمانی دموی چت نیست. باید مورد کاربرد، مرز داده، لایهٔ بازیابی، کنترل هزینه و مسیر ممیزی را قبل از اتصال به سیستم‌های حیاتی طراحی کنید."
  },
  "logistics-product-thinking": {
    "slug": "logistics-product-thinking",
    "tag": "طراحی محصول",
    "tagFilter": "product",
    "title": "تفکر محصولی در طراحی سیستم‌های پیچیده لجستیکی؛ چگونه مسئله واقعی را حل کنیم؟",
    "date": "۲۰ مرداد ۱۴۰۳",
    "read": "۱۲ دقیقه",
    "hero": "assets/images/article/logistics-product-thinking-hero.webp",
    "lead": "در لجستیک فیچر جذاب آسان است؛ حل گره عملیات سخت. سیستم توزیع هوشمند وقتی موفق می‌شود که محصول وضعیت‌ها، استثناها و تصمیم‌های لحظه‌ای اپراتور را جدی بگیرد — نه فقط نقشه و ترکینگ زیبا."
  },
  "modern-ui-2026": {
    "slug": "modern-ui-2026",
    "tag": "UI/UX",
    "tagFilter": "uiux",
    "title": "اصول طراحی رابط‌های کاربری مدرن در سال ۲۰۲۶ و چالش‌های تعاملی جدید",
    "date": "۱۴ اردیبهشت ۱۴۰۵",
    "read": "۸ دقیقه",
    "hero": "assets/images/article/modern-ui-2026-hero.webp",
    "lead": "UI مدرن ۲۰۲۶ یعنی وضوح، حرکت هدفمند و آمادگی برای محتوای تولیدشده توسط مدل — نه گرادیان بنفش و کارت‌های تزئینی. چالش جدید: سفرهای طولانی وب‌اپ و تعامل با خروجی غیرقطعی AI."
  },
  "mvp-scope": {
    "slug": "mvp-scope",
    "tag": "استارتاپ",
    "tagFilter": "startup",
    "title": "دامنه MVP را چطور ببندیم تا لانچ اول هم ارزش بسازد هم قابل‌ساخت بماند؟",
    "date": "۱۰ بهمن ۱۴۰۴",
    "read": "۷ دقیقه",
    "hero": "assets/images/article/mvp-scope-hero.webp",
    "lead": "MVP نسخهٔ ناقص دلخواه بنیان‌گذار نیست؛ کوچک‌ترین محصولی است که فرضیهٔ ارزش را در بازار واقعی می‌آزماید. مرز اشتباه = سوخت بودجه یا لانچ بی‌معنا."
  },
  "nextjs-scale-seo": {
    "slug": "nextjs-scale-seo",
    "tag": "توسعه",
    "tagFilter": "dev",
    "title": "توسعه فرانت‌اند با فریمورک Next.js: راهنمای عملی پایداری و سئو در مقیاس بزرگ",
    "date": "۱۵ فروردین ۱۴۰۵",
    "read": "۱۰ دقیقه",
    "hero": "assets/images/article/nextjs-scale-seo-hero.webp",
    "lead": "Next.js در مقیاس تجاری فقط «SSR روشن» نیست. باید استراتژی رندر، مرز کلاینت/سرور، تصویر، متادیتا و مشاهده‌پذیری را طوری بچینید که هم خزنده راضی باشد هم کاربر روی شبکهٔ واقعی."
  },
  "product-metrics": {
    "slug": "product-metrics",
    "tag": "طراحی محصول",
    "tagFilter": "product",
    "title": "از ونیته‌متریک تا سیگنال تصمیم: کدام عدد محصول را جلو می‌برد؟",
    "date": "۵ دی ۱۴۰۴",
    "read": "۶ دقیقه",
    "hero": "assets/images/article/product-metrics-hero.webp",
    "lead": "داشبورد شلوغ تصمیم نمی‌سازد. تیم محصول به چند سیگنال نیاز دارد که رفتار واقعی و سلامت کسب‌وکار را نشان دهد — نه فقط نمودارهای زیبا."
  },
  "product-validation": {
    "slug": "product-validation",
    "tag": "طراحی محصول",
    "tagFilter": "product",
    "title": "چگونه قبل از کدنویسی بیهوده، فرضیات اصلی محصول را اعتبارسنجی کنیم؟",
    "date": "۲۹ فروردین ۱۴۰۵",
    "read": "۵ دقیقه",
    "hero": "assets/images/article/product-validation-hero.webp",
    "lead": "کدنویسی بدون اعتبارسنجی گران‌ترین راه یادگیری است. قبل از اسپرینت سنگین، فرضیه‌های ارزش، تمایل به پرداخت و قابلیت استفاده را با آزمایش‌های ارزان جدا کنید."
  },
  "technical-seo-js": {
    "slug": "technical-seo-js",
    "tag": "مارکتینگ",
    "tagFilter": "marketing",
    "title": "اصول سئوی تکنیکال برای پلتفرم‌های مدرن جاوا اسکریپت در سال جدید",
    "date": "۲ اسفند ۱۴۰۴",
    "read": "۷ دقیقه",
    "hero": "assets/images/article/technical-seo-js-hero.webp",
    "lead": "ربات گوگل React را «اجرا» می‌کند اما همیشه به‌موقع و کامل نه. سئوی تکنیکال در استک JS یعنی HTML معنادار، بودجهٔ خزش، نقشهٔ سایت تمیز و Core Web Vitals سالم."
  }
};
  global.HASH_ARTICLES_BY_SLUG = BY_SLUG;
  global.HASH_ARTICLE_DEFAULT = BY_SLUG['digital-product-guide'];
})(typeof window !== 'undefined' ? window : this);
