#!/usr/bin/env python3
"""Generate static article pages from js/articles-data.js.

Project/service generation lives in:
  scripts/build-projects.py
  scripts/build-services.py

Output:
  article/<slug>/index.html
  js/articles-index.js

Usage:
  python3 scripts/build-content.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from hash_content import (  # noqa: E402
    BASE,
    ROOT,
    SERVICE_LABELS,
    abs_url,
    article_url,
    escape_html,
    listing_fields,
    load_article_graph,
    load_articles,
    load_project_cards,
    load_solution_labels,
    local_asset_path,
)
GENERATED_BANNER = (
    "<!-- Generated by scripts/build-content.py — do not edit by hand. "
    "Source: js/articles-data.js -->"
)


def validate_articles(
    articles: dict[str, dict[str, Any]],
    graph: dict[str, dict[str, Any]],
    projects: dict[str, dict[str, str]],
) -> list[str]:
    errors: list[str] = []
    service_dirs = {p.name for p in (ROOT / "service").iterdir() if p.is_dir()}

    for slug, article in articles.items():
        if article.get("slug") != slug:
            errors.append(f'Article "{slug}": slug field mismatch')
        for field in ("title", "lead", "hero", "author", "sections", "blocks", "date", "read", "tag"):
            if not article.get(field):
                errors.append(f'Article "{slug}": missing required field {field}')
        author = article.get("author") or {}
        for field in ("name", "role", "avatar", "bio", "aboutTitle"):
            if not author.get(field):
                errors.append(f'Article "{slug}": missing author.{field}')

        for rel in article.get("related") or []:
            rslug = rel.get("slug")
            if rslug and rslug not in articles:
                errors.append(f'Article "{slug}": related points to missing article "{rslug}"')
            img = rel.get("image")
            path = local_asset_path(img or "")
            if path and not path.is_file():
                errors.append(
                    f'Article "{slug}" related "{rslug}" references missing asset:\n  {img}'
                )

        for key in ("hero", "inline"):
            ref = article.get(key)
            path = local_asset_path(ref or "")
            if ref and path and not path.is_file():
                errors.append(f'Article "{slug}" references missing asset:\n  {ref}')

        avatar = (article.get("author") or {}).get("avatar")
        path = local_asset_path(avatar or "")
        if avatar and path and not path.is_file():
            errors.append(f'Article "{slug}" references missing author avatar:\n  {avatar}')

        rel = graph.get(slug) or {}
        for pslug in rel.get("projects") or []:
            if pslug not in projects:
                errors.append(f'Article "{slug}": content-graph project missing: {pslug}')
            else:
                hero = projects[pslug]["hero"]
                path = local_asset_path(hero)
                if path and not path.is_file():
                    errors.append(
                        f'Article "{slug}" related project "{pslug}" missing asset:\n  {hero}'
                    )
        for sslug in rel.get("services") or []:
            if sslug not in service_dirs:
                errors.append(f'Article "{slug}": content-graph service missing: {sslug}')

    return errors


def render_body(article: dict[str, Any]) -> str:
    parts: list[str] = []
    blocks = article.get("blocks") or []
    for i, block in enumerate(blocks):
        parts.append(f'<section class="article-section" id="{escape_html(block["id"])}">')
        parts.append(
            f'<h2 class="article-section__heading">{escape_html(block.get("heading", ""))}</h2>'
        )
        for p in block.get("paragraphs") or []:
            parts.append(f'<p class="article-section__p">{escape_html(p)}</p>')
        if block.get("listTitle"):
            parts.append(
                f'<h3 class="article-section__sub">{escape_html(block["listTitle"])}</h3>'
            )
        if block.get("list"):
            items = "".join(f"<li>{escape_html(item)}</li>" for item in block["list"])
            parts.append(f'<ul class="article-list">{items}</ul>')
        if block.get("showInline") and article.get("inline"):
            caption = escape_html(article.get("inlineCaption") or "")
            parts.append(
                '<figure class="article-figure">'
                f'<img src="{escape_html(article["inline"])}" alt="{caption}" '
                'width="759" height="379" loading="lazy" decoding="async">'
                f"<figcaption>{caption}</figcaption>"
                "</figure>"
            )
        if block.get("showTip") and article.get("tip"):
            tip = article["tip"]
            parts.append(
                '<aside class="article-tip">'
                '<div class="article-tip__head">'
                '<img src="assets/icons/article/info.svg" alt="" width="18" height="18">'
                f"<strong>{escape_html(tip.get('title', ''))}</strong></div>"
                f"<p>{escape_html(tip.get('body', ''))}</p></aside>"
            )
        parts.append("</section>")
        if i == 0 and article.get("quote") and article["quote"].get("text"):
            q = article["quote"]
            parts.append(
                '<blockquote class="article-quote">'
                f'<p class="article-quote__text">{escape_html(q["text"])}</p>'
                f'<cite class="article-quote__cite">— {escape_html(q.get("cite", ""))}</cite>'
                "</blockquote>"
            )
    if article.get("closing"):
        parts.append(
            f'<p class="article-section__p article-section__p--closing">'
            f'{escape_html(article["closing"])}</p>'
        )
    return "\n            ".join(parts)


def render_toc(article: dict[str, Any]) -> str:
    items = []
    for index, section in enumerate(article.get("sections") or []):
        active = " is-active" if index == 0 else ""
        items.append(
            f'<li><a class="article-toc__link{active}" href="#{escape_html(section["id"])}">'
            f'{escape_html(section["label"])}</a></li>'
        )
    return "\n              ".join(items)


def render_related(article: dict[str, Any]) -> str:
    cards = []
    for post in article.get("related") or []:
        cards.append(
            f'<a class="article-related__card" href="/article/{escape_html(post["slug"])}/" '
            f'data-cta="view-article" data-cta-location="article-related" '
            f'data-content-slug="{escape_html(post["slug"])}">'
            f'<div class="article-related__media">'
            f'<img src="{escape_html(post.get("image", ""))}" '
            f'alt="{escape_html(post.get("title", ""))}" '
            'width="384" height="240" loading="lazy" decoding="async"></div>'
            f'<div class="article-related__body">'
            f'<span class="article-related__tag">{escape_html(post.get("tag", ""))}</span>'
            f'<h3 class="article-related__title">{escape_html(post.get("title", ""))}</h3>'
            f'<div class="article-related__meta"><time>{escape_html(post.get("date", ""))}</time>'
            f'<span>زمان مطالعه: {escape_html(post.get("read", ""))}</span></div>'
            f"</div></a>"
        )
    return "\n          ".join(cards)


def render_projects(
    article: dict[str, Any],
    rel: dict[str, Any],
    projects: dict[str, dict[str, str]],
) -> tuple[str, bool]:
    cards = []
    for pslug in rel.get("projects") or []:
        p = projects.get(pslug)
        if not p:
            continue
        cards.append(
            f'<a class="article-proof__card" href="/project/{escape_html(p["slug"])}/" '
            f'data-cta="content-bridge" data-cta-location="article-bridge" '
            f'data-from-type="article" data-from-slug="{escape_html(article["slug"])}" '
            f'data-to-type="project" data-to-slug="{escape_html(p["slug"])}" '
            f'data-content-slug="{escape_html(article["slug"])}" '
            f'data-project-slug="{escape_html(p["slug"])}">'
            f'<figure class="article-proof__media">'
            f'<img src="{escape_html(p["hero"])}" alt="{escape_html(p["name"])}" '
            'width="640" height="400" loading="lazy" decoding="async"></figure>'
            f'<div class="article-proof__body">'
            f'<span class="article-proof__industry">{escape_html(p["industry"])}</span>'
            f'<h3 class="article-proof__title">{escape_html(p["name"])}</h3>'
            f'<p class="article-proof__meta">{escape_html(p["services"])}</p>'
            f'<p class="article-proof__lead">{escape_html(p["lead"])}</p>'
            f'<span class="article-proof__cta">مطالعه کیس‌استادی {escape_html(p["name"])}</span></div></a>'
        )
    return "\n          ".join(cards), bool(cards)


def render_services(article: dict[str, Any], rel: dict[str, Any]) -> tuple[str, bool]:
    cards = []
    for sslug in rel.get("services") or []:
        label = SERVICE_LABELS.get(sslug, sslug)
        cards.append(
            f'<a class="article-service-link" href="/service/{escape_html(sslug)}/" '
            f'data-cta="content-bridge" data-cta-location="article-bridge" '
            f'data-from-type="article" data-from-slug="{escape_html(article["slug"])}" '
            f'data-to-type="service" data-to-slug="{escape_html(sslug)}" '
            f'data-content-slug="{escape_html(article["slug"])}" '
            f'data-service-slug="{escape_html(sslug)}">آشنایی با خدمت {escape_html(label)}</a>'
        )
    return "\n            ".join(cards), bool(cards)


def render_solutions(article: dict[str, Any], rel: dict[str, Any]) -> tuple[str, bool]:
    labels = load_solution_labels()
    cards = []
    for sslug in (rel.get("solutions") or [])[:2]:
        label = labels.get(sslug, sslug)
        cards.append(
            f'<a class="article-service-link article-service-link--solution" '
            f'href="/solutions/{escape_html(sslug)}/" '
            f'data-cta="content-bridge" data-cta-location="article-bridge" '
            f'data-from-type="article" data-from-slug="{escape_html(article["slug"])}" '
            f'data-to-type="solution" data-to-slug="{escape_html(sslug)}" '
            f'data-content-slug="{escape_html(article["slug"])}">'
            f'بررسی مسیر {escape_html(label)}</a>'
        )
    return "\n            ".join(cards), bool(cards)


def json_ld(article: dict[str, Any], canonical: str, page_desc: str, og_image: str) -> str:
    graph = [
        {
            "@type": "BlogPosting",
            "headline": article["title"],
            "description": page_desc,
            "url": canonical,
            "image": og_image,
            "inLanguage": "fa-IR",
            "mainEntityOfPage": {"@type": "WebPage", "@id": canonical},
            "author": {
                "@type": "Person",
                "name": (article.get("author") or {}).get("name") or "استودیو هش",
            },
            "publisher": {
                "@type": "Organization",
                "name": "استودیو هش",
                "url": f"{BASE}/",
                "logo": {
                    "@type": "ImageObject",
                    "url": abs_url("assets/images/home/logo.png"),
                },
            },
        },
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "خانه",
                    "item": f"{BASE}/",
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "مقالات",
                    "item": f"{BASE}/blog.html",
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": article["title"],
                    "item": canonical,
                },
            ],
        },
    ]
    payload = {"@context": "https://schema.org", "@graph": graph}
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def render_article(
    article: dict[str, Any],
    rel: dict[str, Any],
    projects: dict[str, dict[str, str]],
) -> str:
    slug = article["slug"]
    title = article["title"]
    page_title = f"{title} | استودیو هش"
    page_desc = (article.get("lead") or "")[:160]
    canonical = article_url(slug)
    og_image = abs_url(article.get("hero") or "assets/images/home/logo.png")
    author = article.get("author") or {}
    body = render_body(article)
    toc = render_toc(article)
    related = render_related(article)
    project_html, has_projects = render_projects(article, rel, projects)
    service_html, has_services = render_services(article, rel)
    solution_html, has_solutions = render_solutions(article, rel)
    cta_title = (rel.get("ctaTitle") or "").strip()
    cta_body = (rel.get("ctaBody") or "").strip()
    if not cta_title or not cta_body:
        raise RuntimeError(
            f'Article "{article["slug"]}": missing content-graph ctaTitle/ctaBody'
        )
    ld = json_ld(article, canonical, page_desc, og_image)
    hero_alt = escape_html(title)
    avatar_alt = escape_html(f'تصویر {author.get("name", "نویسنده")}')

    proof_section = ""
    if has_projects:
        proof_section = f"""
    <section class="article-proof" data-block="article-projects">
      <div class="container">
        <span class="article-related__badge">اثبات در کار واقعی</span>
        <h2 class="article-related__heading">این رویکرد را در این پروژه‌ها دیده‌ایم</h2>
        <div class="article-proof__grid" data-list="article-projects">
          {project_html}
        </div>
      </div>
    </section>"""

    bridge_links = "\n            ".join(
        x for x in [service_html, solution_html] if x
    )
    service_section = ""
    if has_services or has_solutions:
        service_section = f"""
    <section class="article-service-cta" data-block="article-services">
      <div class="container">
        <div class="article-service-cta__card">
          <h2 class="article-service-cta__title">اگر این مسئله برای محصول شما هم وجود دارد…</h2>
          <p class="article-service-cta__body" data-field="service-context">{escape_html(cta_body)}</p>
          <div class="article-service-cta__links" data-list="article-services">
            {bridge_links}
          </div>
          <p class="article-service-cta__fit"><a href="/#service-fit" data-cta="service-fit-guide" data-cta-location="article">نمی‌دانید کدام خدمت مناسب است؟</a></p>
        </div>
      </div>
    </section>"""

    related_section = ""
    if related:
        related_section = f"""
    <section class="article-related" aria-labelledby="article-related-title">
      <div class="container">
        <span class="article-related__badge">دانستنی‌های بیشتر</span>
        <h2 class="article-related__heading" id="article-related-title">مطالعه مقالات مرتبط</h2>
        <div class="article-related__grid" data-list="related">
          {related}
        </div>
      </div>
    </section>"""

    return f"""<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{escape_html(page_desc)}">
  <meta name="robots" content="index,follow">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="article">
  <meta property="og:locale" content="fa_IR">
  <meta property="og:site_name" content="استودیو هش">
  <meta property="og:title" content="{escape_html(page_title)}">
  <meta property="og:description" content="{escape_html(page_desc)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{og_image}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape_html(page_title)}">
  <meta name="twitter:description" content="{escape_html(page_desc)}">
  <meta name="twitter:image" content="{og_image}">
  <link rel="preload" as="image" href="{escape_html(article.get('hero', ''))}">
  <title>{escape_html(page_title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;700;800&display=swap" id="hash-font-vazirmatn">
  <link rel="icon" href="assets/images/home/logo.png" type="image/png">
  <link rel="stylesheet" href="css/tokens.css">
  <link rel="stylesheet" href="css/reset.css">
  <link rel="stylesheet" href="css/base.css">
  <link rel="stylesheet" href="css/home.css">
  <link rel="stylesheet" href="css/home-sections.css">
  <link rel="stylesheet" href="css/home-responsive.css">
  <link rel="stylesheet" href="css/article.css">
  <script type="application/ld+json" id="article-jsonld">{ld}</script>
</head>
<body class="home-page article-page" data-slug="{escape_html(slug)}">
{GENERATED_BANNER}

  <div class="top-bar">
    <div class="container top-bar__inner">
      <p class="top-bar__text">برای شروع پروژه جدید آماده‌ایم — درباره ایده‌تان با ما صحبت کنید</p>
      <a href="contact.html" class="top-bar__btn">شروع پروژه</a>
    </div>
  </div>

  <header class="home-header" id="site-header">
    <div class="container home-header__inner">
      <a href="index.html" class="home-header__logo">
        <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
        <span class="home-header__logo-text">استودیو هش</span>
      </a>

      <nav class="home-header__nav" id="main-nav" aria-label="منوی اصلی">
        <a href="index.html" class="home-header__link">خانه</a>
        <a href="services.html" class="home-header__link">خدمات</a>
        <a href="projects.html" class="home-header__link">پروژه‌ها</a>
        <a href="about.html" class="home-header__link">درباره ما</a>
        <a href="blog.html" class="home-header__link is-active">بلاگ</a>
        <a href="contact.html" class="home-header__link">تماس با ما</a>
      </nav>

      <div class="home-header__actions">
        <a href="contact.html" class="btn btn--primary btn--header">شروع پروژه</a>
        <a href="contact.html" class="home-header__profile" aria-label="تماس با ما">
          <img src="assets/icons/profile.svg" alt="" width="39" height="39">
        </a>
        <button class="home-header__toggle" aria-label="باز کردن منو" aria-expanded="false" aria-controls="main-nav">
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </div>
  </header>

  <main>
    <section class="article-hero">
      <div class="container">
        <nav class="article-breadcrumb" aria-label="مسیر">
          <a href="index.html">خانه</a>
          <span class="article-breadcrumb__sep" aria-hidden="true">›</span>
          <a href="blog.html">مقالات</a>
          <span class="article-breadcrumb__sep" aria-hidden="true">›</span>
          <span class="article-breadcrumb__current">{escape_html(title)}</span>
        </nav>

        <span class="article-hero__tag">{escape_html(article.get("tag", ""))}</span>
        <h1 class="article-hero__title">{escape_html(title)}</h1>

        <div class="article-hero__meta">
          <div class="article-hero__author">
            <img class="article-hero__avatar" src="{escape_html(author.get("avatar", ""))}" alt="{avatar_alt}" width="52" height="52">
            <div>
              <div class="article-hero__author-name">{escape_html(author.get("name", ""))}</div>
              <div class="article-hero__author-role">{escape_html(author.get("role", ""))}</div>
            </div>
          </div>
          <div class="article-hero__stats">
            <time>{escape_html(article.get("date", ""))}</time>
            <span class="article-hero__dot" aria-hidden="true"></span>
            <span>زمان مطالعه: {escape_html(article.get("read", ""))}</span>
          </div>
        </div>

        <div class="article-hero__media">
          <img src="{escape_html(article.get("hero", ""))}" alt="{hero_alt}" width="1239" height="519" loading="eager" decoding="async" fetchpriority="high">
        </div>
      </div>
    </section>

    <section class="article-main">
      <div class="container">
        <div class="article-layout">
          <article class="article-content">
            <p class="article-lead">{escape_html(article.get("lead", ""))}</p>
            <div data-list="body">
            {body}
            </div>
          </article>

          <aside class="article-aside">
            <nav class="article-toc" aria-label="سرفصل‌های مقاله">
              <h2 class="article-toc__title">سرفصل‌های این مقاله</h2>
              <ol class="article-toc__list" data-list="toc">
              {toc}
              </ol>
            </nav>
            <div class="article-share">
              <h2 class="article-share__title">ارسال این مطلب برای دیگران</h2>
              <div class="article-share__row">
                <a class="article-share__btn" href="#" aria-label="لینکدین"><img src="assets/icons/article/linkedin.svg" alt="" width="18" height="18"></a>
                <a class="article-share__btn" href="#" aria-label="توییتر"><img src="assets/icons/article/x.svg" alt="" width="18" height="18"></a>
                <a class="article-share__btn" href="#" aria-label="اشتراک"><img src="assets/icons/article/share.svg" alt="" width="18" height="18"></a>
                <a class="article-share__btn" href="#" aria-label="وب"><img src="assets/icons/article/web.svg" alt="" width="18" height="18"></a>
              </div>
            </div>
          </aside>
        </div>

        <aside class="article-author" aria-label="درباره نویسنده">
          <img class="article-author__avatar" src="{escape_html(author.get("avatar", ""))}" alt="{avatar_alt}" width="156" height="156">
          <div>
            <h2 class="article-author__title">{escape_html(author.get("aboutTitle", ""))}</h2>
            <p class="article-author__bio">{escape_html(author.get("bio", ""))}</p>
            <div class="article-author__row">
              <div class="article-author__social">
                <a href="https://www.instagram.com/hashstudio.ir/" aria-label="اینستاگرام" target="_blank" rel="noopener noreferrer"><img src="assets/icons/article/instagram.svg" alt="" width="18" height="18"></a>
                <a class="article-author__social-li" href="#" aria-label="لینکدین"><img src="assets/icons/article/linkedin.svg" alt="" width="18" height="18"></a>
                <a class="article-author__social-x" href="#" aria-label="توییتر"><img src="assets/icons/article/x.svg" alt="" width="18" height="18"></a>
              </div>
              <a class="article-author__more" href="blog.html?filter={escape_html(article.get("tagFilter", "all"))}">{escape_html(author.get("moreLabel", "مشاهده مقالات بیشتر"))}</a>
            </div>
          </div>
        </aside>
      </div>
    </section>
{related_section}
{proof_section}
{service_section}

    <section class="article-newsletter" aria-labelledby="article-newsletter-title">
      <div class="container">
        <div class="article-newsletter__card">
          <div class="article-newsletter__content">
            <h2 class="article-newsletter__title" id="article-newsletter-title">{escape_html(cta_title)}</h2>
            <p class="article-newsletter__desc">{escape_html(cta_body)}</p>
            <a class="article-newsletter__submit" href="contact.html" data-article-cta data-cta="start-project" data-cta-location="article" data-content-slug="{escape_html(slug)}">شروع پروژه</a>
          </div>
        </div>
      </div>
    </section>
  </main>

  <footer class="home-footer">
    <div class="container">
      <div class="home-footer__grid">
        <div class="home-footer__brand">
          <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
          <div class="home-footer__brand-name">استودیو هش</div>
          <p class="home-footer__brand-desc">طراحی و توسعه محصولات دیجیتال برای استارتاپ‌ها و شرکت‌های پیشرو — از ایده تا تجربه‌ای که کاربران عاشقش می‌شوند.</p>
          <div class="home-footer__location">
            <span class="home-footer__location-icon" aria-hidden="true">📍</span>
            <span data-studio="address-short">تهران، یوسف‌آباد، جهان‌آرا، کوچه ۴۳</span>
          </div>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">دسترسی سریع</h3>
          <nav class="home-footer__links" aria-label="لینک‌های فوتر">
            <a href="index.html" class="home-footer__link">خانه اصلی</a>
            <a href="services.html" class="home-footer__link">خدمات</a>
            <a href="projects.html" class="home-footer__link">پروژه‌ها و نمونه‌کارها</a>
            <a href="about.html" class="home-footer__link">درباره ما</a>
            <a href="blog.html" class="home-footer__link">وبلاگ تخصصی</a>
            <a href="contact.html" class="home-footer__link">تماس با ما</a>
          </nav>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">خدمات ما</h3>
          <nav class="home-footer__links">
            <a href="/service/product/" class="home-footer__link">طراحی محصول</a>
            <a href="/service/ui-ux/" class="home-footer__link">طراحی UI/UX</a>
            <a href="/service/web/" class="home-footer__link">توسعه وب مدرن</a>
            <a href="/service/mobile/" class="home-footer__link">توسعه اپلیکیشن موبایل</a>
            <a href="/service/mvp/" class="home-footer__link">راه‌اندازی MVP</a>
            <a href="/service/ai/" class="home-footer__link">یکپارچه‌سازی هوش مصنوعی</a>
            <a href="/service/seo/" class="home-footer__link">سئو و رشد</a>
            <a href="/service/consulting/" class="home-footer__link">مشاوره محصول</a>
          </nav>
        </div>
        <div class="home-footer__newsletter-col">
          <h3 class="home-footer__heading">پروژه بعدی شما</h3>
          <p class="home-footer__newsletter-desc">ایده، محصول نیمه‌کاره یا بازطراحی — مسیر را با هم مشخص می‌کنیم.</p>
          <a class="btn btn--primary" href="/contact.html" data-cta="start-project" data-cta-location="footer">شروع پروژه</a>
          <div class="home-footer__social" data-studio="social" data-studio-social-class="home-footer__social-link">
            <a href="https://www.instagram.com/hashstudio.ir/" class="home-footer__social-link" aria-label="اینستاگرام" target="_blank" rel="noopener noreferrer">IG</a>
          </div>
        </div>
      </div>
      <div class="home-footer__bottom">
        <span>تمامی حقوق مادی و معنوی محفوظ است © ۱۴۰۵ استودیو هش</span>
        <span>طراحی و توسعه با ■ در استودیو هش</span>
      </div>
    </div>
  </footer>

  <script src="js/studio-info.js"></script>
  <script src="js/analytics.js"></script>
  <script src="js/studio-chrome.js"></script>
  <script src="js/main.js"></script>
  <script src="js/article.js"></script>
</body>
</html>
"""


def write_articles_index(articles: dict[str, dict[str, Any]]) -> Path:
    index = {slug: listing_fields(article) for slug, article in articles.items()}
    # Stable key order
    ordered = {slug: index[slug] for slug in sorted(index)}
    payload = json.dumps(ordered, ensure_ascii=False, indent=2)
    default = "digital-product-guide" if "digital-product-guide" in ordered else next(iter(ordered))
    content = f"""/* Generated by scripts/build-content.py — listing fields only.
 * Source of truth: js/articles-data.js
 * Do not edit by hand.
 */
(function (global) {{
  'use strict';
  var BY_SLUG = {payload};
  global.HASH_ARTICLES_BY_SLUG = BY_SLUG;
  global.HASH_ARTICLE_DEFAULT = BY_SLUG['{default}'];
}})(typeof window !== 'undefined' ? window : this);
"""
    out = ROOT / "js/articles-index.js"
    out.write_text(content, encoding="utf-8")
    return out


def main() -> int:
    articles = load_articles()
    graph = load_article_graph()
    projects = load_project_cards()

    if not graph:
        print("BUILD FAILED — content-graph ARTICLES parse returned empty")
        return 1
    missing_graph = sorted(set(articles) - set(graph))
    if missing_graph:
        print("BUILD FAILED — articles missing content-graph entries:")
        for slug in missing_graph:
            print(f"ERROR: {slug}")
        return 1

    errors = validate_articles(articles, graph, projects)
    if errors:
        print("BUILD FAILED — validation errors:")
        for err in errors:
            print(f"ERROR: {err}")
        return 1

    article_root = ROOT / "article"
    article_root.mkdir(exist_ok=True)

    # Remove obsolete generated article dirs not in data
    existing = {p.name for p in article_root.iterdir() if p.is_dir()} if article_root.exists() else set()
    for stale in sorted(existing - set(articles)):
        stale_index = article_root / stale / "index.html"
        if stale_index.exists() and "Generated by scripts/build-content.py" in stale_index.read_text(
            encoding="utf-8", errors="ignore"
        ):
            stale_index.unlink()
            try:
                (article_root / stale).rmdir()
            except OSError:
                pass
            print(f"Removed stale article/{stale}/")

    for slug, article in sorted(articles.items()):
        rel = graph.get(slug) or {
            "projects": [],
            "services": [],
            "ctaTitle": "",
            "ctaBody": "",
        }
        html = render_article(article, rel, projects)
        out_dir = article_root / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(html, encoding="utf-8")

    index_path = write_articles_index(articles)
    print(f"Generated {len(articles)} article pages → article/<slug>/index.html")
    print(f"Generated {index_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
