#!/usr/bin/env python3
"""Static HTML renderer for project case-study pages."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from hash_content import BASE, abs_url, escape_html, project_url

GENERATED_BANNER = (
    "<!-- Generated by scripts/build-projects.py — do not edit by hand. "
    "Source: js/projects-data.js -->"
)

SERVICE_CATALOG = {
    "product": {"name": "طراحی محصول", "href": "/service/product/"},
    "ui-ux": {"name": "طراحی UI/UX", "href": "/service/ui-ux/"},
    "web": {"name": "توسعه وب", "href": "/service/web/"},
    "mobile": {"name": "توسعه موبایل", "href": "/service/mobile/"},
    "mvp": {"name": "راه‌اندازی MVP", "href": "/service/mvp/"},
    "ai": {"name": "هوش مصنوعی", "href": "/service/ai/"},
    "seo": {"name": "سئو و رشد", "href": "/service/seo/"},
    "consulting": {"name": "مشاوره محصول", "href": "/service/consulting/"},
}


def _hidden(show: bool) -> str:
    return "" if show else " hidden"


def _attr(value: Any) -> str:
    return escape_html(value)


def _related_score(item: dict[str, Any], project: dict[str, Any]) -> float:
    score = 0.0
    if item.get("industry") and item.get("industry") == project.get("industry"):
        score += 3
    project_slugs = set(project.get("serviceSlugs") or [])
    for slug in item.get("serviceSlugs") or []:
        if slug in project_slugs:
            score += 1
    project_filters = set(project.get("filters") or [])
    for key in item.get("filters") or []:
        if key in project_filters:
            score += 0.5
    return score


def _pick_related(project: dict[str, Any], projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    others = [p for p in projects if p.get("slug") != project.get("slug")]
    others.sort(key=lambda item: _related_score(item, project), reverse=True)
    return others[:3]


def _gallery_items(project: dict[str, Any], images: dict[str, Any]) -> list[dict[str, str]]:
    sections = images.get("sections") or []
    if sections:
        return [
            {"src": s.get("src") or "", "alt": s.get("alt") or ""}
            for s in sections
            if s.get("src")
        ]
    name = project.get("name") or ""
    fallback = [
        {"src": images.get("hero") or "", "alt": f"شات دسکتاپ {name}"},
        {"src": images.get("pixel") or "", "alt": f"پیش‌نمایش {name}"},
        {"src": images.get("skeleton") or "", "alt": f"اسکلت رابط {name}"},
    ]
    return [item for item in fallback if item["src"]]


def _gallery_mod(index: int) -> str:
    if index in (0, 5, 8):
        return "pd-gallery__item--full"
    if index in (3, 7):
        return "pd-gallery__item--feature"
    return "pd-gallery__item--pair"


def _json_ld(project: dict[str, Any], canonical: str, page_desc: str, og_image: str) -> str:
    creative: dict[str, Any] = {
        "@type": "CreativeWork",
        "name": project.get("name") or "",
        "headline": project.get("title") or "",
        "description": page_desc,
        "url": canonical,
        "inLanguage": "fa-IR",
        "creator": {
            "@type": "Organization",
            "name": "استودیو هش",
            "url": f"{BASE}/",
        },
    }
    if og_image:
        creative["image"] = og_image
    if project.get("industry"):
        creative["about"] = project["industry"]
    graph = [
        creative,
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "خانه", "item": f"{BASE}/"},
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "پروژه‌ها",
                    "item": f"{BASE}/projects.html",
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": project.get("name") or "",
                    "item": canonical,
                },
            ],
        },
    ]
    return json.dumps(
        {"@context": "https://schema.org", "@graph": graph},
        ensure_ascii=False,
        separators=(",", ":"),
    )


def _meta_item(label: str, value: str) -> str:
    show = bool(str(value or "").strip())
    return (
        f'<div class="pd-meta__item"{_hidden(show)}>'
        f"<dt>{escape_html(label)}</dt>"
        f"<dd>{escape_html(value or '')}</dd>"
        f"</div>"
    )


def render_project(
    project: dict[str, Any],
    projects: list[dict[str, Any]],
    articles: dict[str, dict[str, Any]],
    graph_projects: dict[str, Any],
) -> str:
    slug = project["slug"]
    name = project.get("name") or ""
    title = project.get("title") or ""
    lead = project.get("lead") or ""
    industry = str(project.get("industry") or "").strip()
    page_title = (
        f"{name} | کیس‌استادی {industry} | استودیو هش"
        if industry
        else f"{name} | کیس‌استادی محصول دیجیتال | استودیو هش"
    )
    summary = project.get("summary") or {}
    page_desc = lead or (summary.get("body") or "")
    if len(page_desc) > 170:
        page_desc = page_desc[:167].rstrip() + "…"
    canonical = project_url(slug)
    images = project.get("images") or {}
    hero_src = images.get("hero") or ""
    og_image = abs_url(hero_src) if hero_src else abs_url("assets/images/home/logo.png")
    ld = _json_ld(project, canonical, page_desc, og_image if hero_src else "")

    challenge = project.get("challenge") or {}
    research = project.get("research") or {}
    ux = project.get("ux") or {}
    design_system = project.get("designSystem") or {}
    tech = project.get("tech") or {}
    quote = project.get("quote") or {}
    outcome = project.get("outcome") or {}
    closing = project.get("closing") or {}
    early_metrics = project.get("earlyMetrics") or []
    kpis = project.get("kpis") or []
    service_slugs = project.get("serviceSlugs") or []
    gallery = _gallery_items(project, images)

    by_slug = {p["slug"]: p for p in projects}
    nxt = by_slug.get(project.get("nextSlug") or "")
    prev = by_slug.get(project.get("prevSlug") or "")
    related = _pick_related(project, projects)

    show_summary = bool(summary.get("heading") or summary.get("body"))
    show_early = len(early_metrics) > 0
    show_challenge = bool(
        challenge.get("heading") or challenge.get("body") or (challenge.get("goals") or [])
    )
    show_research = bool(research.get("heading") or (research.get("findings") or []))
    show_ux = bool(ux.get("heading") or (ux.get("cards") or []))
    colors = design_system.get("colors") or []
    type_scale = design_system.get("type") or []
    spacing_scale = design_system.get("spacing") or []
    show_ds = bool(colors or type_scale or spacing_scale)
    show_gallery = len(gallery) > 0
    show_tech = bool(
        tech.get("heading")
        or tech.get("body")
        or (tech.get("stack") or [])
        or (tech.get("layers") or [])
    )
    show_outcome = bool(outcome.get("body")) or len(kpis) > 0
    show_quote = bool(quote.get("text"))
    show_closing = bool(closing.get("body"))
    show_services = len(service_slugs) > 0
    show_related = len(related) > 0
    show_next = nxt is not None

    article_slugs = (graph_projects.get(slug) or {}).get("articles") or []
    article_cards: list[str] = []
    for aslug in article_slugs:
        a = articles.get(aslug)
        if not a:
            continue
        article_cards.append(
            f'<a class="pd-article" href="/article/{_attr(a["slug"])}/" '
            f'data-cta="view-article" data-cta-location="project" '
            f'data-content-slug="{_attr(a["slug"])}" data-project-slug="{_attr(slug)}">'
            f'<span class="pd-article__tag">{escape_html(a.get("tag") or "")}</span>'
            f'<h3 class="pd-article__title">{escape_html(a.get("title") or "")}</h3>'
            f'<p class="pd-article__lead">{escape_html((a.get("lead") or "")[:140])}</p>'
            f'<span class="pd-article__cta">از نگاه استودیو هش</span></a>'
        )
    show_articles = len(article_cards) > 0

    toc_candidates = [
        ("pd-intro", "مقدمه", True),
        ("pd-summary", "خلاصه", show_summary),
        ("pd-challenge", "چالش", show_challenge),
        ("pd-research", "تحقیق", show_research),
        ("pd-ux", "تجربه کاربری", show_ux),
        ("pd-design", "طراحی", show_ds),
        ("pd-gallery", "گالری", show_gallery),
        ("pd-tech", "فناوری", show_tech),
        ("pd-outcome", "نتیجه", show_outcome),
    ]
    toc_items = [(sid, label) for sid, label, visible in toc_candidates if visible]
    show_toc = len(toc_items) >= 3
    toc_html = "\n".join(
        f'<li><a class="pd-toc__link" href="/project/{_attr(slug)}/#{_attr(sid)}">{escape_html(label)}</a></li>'
        for sid, label in toc_items
    )

    early_html = "".join(
        f'<li class="pd-early__item"><div class="pd-early__value">{escape_html(item.get("value") or "")}'
        f'</div><div class="pd-early__label">{escape_html(item.get("label") or "")}</div></li>'
        for item in early_metrics
    )
    goals_html = "".join(
        f"<li>{escape_html(item)}</li>" for item in (challenge.get("goals") or [])
    )
    findings_html = "".join(
        f"<li>{escape_html(item)}</li>" for item in (research.get("findings") or [])
    )

    ux_cards_html_parts: list[str] = []
    for index, card in enumerate(ux.get("cards") or []):
        src = card.get("image")
        if not src:
            section = images.get("sections") or []
            sec = section[index + 1] if index + 1 < len(section) else None
            src = (sec or {}).get("src") if sec else None
            if not src:
                src = images.get("pixel") if index == 0 else images.get("hero")
        src = src or hero_src
        ux_cards_html_parts.append(
            '<article class="pd-ux__card pd-reveal">'
            f'<figure class="pd-ux__media"><img src="{_attr(src)}" alt="{_attr(card.get("title") or "")}" '
            f'width="960" height="540" loading="lazy" decoding="async" '
            f'onerror="this.onerror=null;this.src=\'{_attr(hero_src)}\'"></figure>'
            f'<div class="pd-ux__body"><h3 class="pd-ux__title">{escape_html(card.get("title") or "")}</h3>'
            f'<p class="pd-ux__text">{escape_html(card.get("body") or "")}</p></div></article>'
        )
    ux_html = "".join(ux_cards_html_parts)

    ds_parts: list[str] = []
    if colors:
        chips = "".join(
            f'<li><span class="pd-swatches__chip" style="background:{_attr(c.get("hex") or "")}"></span>'
            f'<span>{escape_html(c.get("name") or "")}</span>'
            f'<span dir="ltr">{escape_html(c.get("hex") or "")}</span></li>'
            for c in colors
        )
        ds_parts.append(
            f'<div><h3 class="pd-ds__label">رنگ‌ها</h3><ul class="pd-swatches">{chips}</ul></div>'
        )
    if type_scale:
        rows = "".join(
            f'<li><span class="pd-type__name">{escape_html(item.get("name") or "")}</span>'
            f'<span>{escape_html(item.get("value") or "")}</span></li>'
            for item in type_scale
        )
        ds_parts.append(
            f'<div><h3 class="pd-ds__label">تایپوگرافی</h3><ul class="pd-type">{rows}</ul></div>'
        )
    if spacing_scale:
        rows = "".join(
            f'<li><span class="pd-spacing__name">{escape_html(item.get("name") or "")}</span>'
            f'<span>{escape_html(item.get("value") or "")}</span></li>'
            for item in spacing_scale
        )
        ds_parts.append(
            f'<div><h3 class="pd-ds__label">فاصله‌گذاری</h3><ul class="pd-spacing">{rows}</ul></div>'
        )
    ds_html = "".join(ds_parts)

    gallery_html = "".join(
        f'<figure class="pd-gallery__item {_gallery_mod(i)} pd-reveal">'
        f'<img src="{_attr(item["src"])}" alt="{_attr(item["alt"])}" width="1280" height="720" '
        f'loading="lazy" decoding="async" '
        f'onerror="this.onerror=null;this.src=\'{_attr(hero_src)}\'"></figure>'
        for i, item in enumerate(gallery)
    )
    layers_html = "".join(f"<li>{escape_html(item)}</li>" for item in (tech.get("layers") or []))
    stack_html = "".join(
        f'<li><span dir="auto">{escape_html(item)}</span></li>' for item in (tech.get("stack") or [])
    )
    kpis_html = "".join(
        f'<li class="pd-reveal"><div class="pd-kpis__value">{escape_html(item.get("value") or "")}</div>'
        f'<div class="pd-kpis__label">{escape_html(item.get("label") or "")}</div></li>'
        for item in kpis
    )
    service_links_html = "".join(
        f'<a class="pd-service-link" href="{_attr(SERVICE_CATALOG[s]["href"])}" '
        f'data-cta="view-service" data-cta-location="project-service" '
        f'data-service-slug="{_attr(s)}" data-project-slug="{_attr(slug)}">'
        f'{escape_html(SERVICE_CATALOG[s]["name"])}</a>'
        for s in service_slugs
        if s in SERVICE_CATALOG
    )
    related_html = "".join(
        f'<a class="pd-related__card pd-reveal" href="/project/{_attr(item["slug"])}/" '
        f'data-cta="view-project" data-cta-location="project-related" '
        f'data-project-slug="{_attr(item["slug"])}">'
        f'<figure class="pd-related__media"><img src="{_attr((item.get("images") or {}).get("hero") or "")}" '
        f'alt="{_attr(item.get("name") or "")}" width="640" height="400" loading="lazy" decoding="async"></figure>'
        f'<div class="pd-related__body">'
        f'<span class="pd-related__industry">{escape_html(item.get("industry") or "")}</span>'
        f'<h3 class="pd-related__title">{escape_html(item.get("name") or "")}</h3>'
        f'<p class="pd-related__lead">{escape_html(item.get("lead") or "")}</p>'
        f'<span class="pd-related__cta">مطالعه تجربه {escape_html(item.get("name") or "")}</span>'
        f"</div></a>"
        for item in related
    )

    # Only show client/role when not the data-file fallback (client=name, role=services)
    raw_client = str(project.get("client") or "").strip()
    raw_role = str(project.get("role") or "").strip()
    services_label = str(project.get("services") or "").strip()
    client = raw_client if raw_client and raw_client != name else ""
    role = raw_role if raw_role and raw_role != services_label else ""
    platform = project.get("platform") or ""
    live_url = str(project.get("url") or "").strip()
    if live_url:
        live_btn = (
            f'<a class="btn btn--primary btn--lg" href="{_attr(live_url)}" '
            f'target="_blank" rel="noopener noreferrer" aria-label="{_attr(f"مشاهده وب‌سایت {name}")}" '
            f'data-cta="external-project" data-cta-location="project-hero" data-project-slug="{_attr(slug)}">'
            f"مشاهده وب‌سایت</a>"
        )
    else:
        live_btn = ""

    challenge_img = images.get("challenge") or images.get("pixel") or ""
    research_img = images.get("research") or images.get("skeleton") or ""
    sections = images.get("sections") or []
    feature_src = ""
    feature_alt = f"پیش‌نمایش محصول {name}"
    if len(sections) > 1 and sections[1].get("src"):
        feature_src = sections[1]["src"]
        feature_alt = sections[1].get("alt") or feature_alt
    else:
        feature_src = images.get("pixel") or hero_src

    prev_href = f"/project/{_attr(prev['slug'])}/" if prev else "projects.html"
    prev_name = prev.get("name") if prev else ""
    next_href = f"/project/{_attr(nxt['slug'])}/" if nxt else "projects.html"
    next_name = nxt.get("name") if nxt else ""
    next_industry = nxt.get("industry") if nxt else ""
    next_lead = nxt.get("lead") if nxt else ""
    next_img = ((nxt.get("images") or {}).get("hero") if nxt else "") or ""

    outcome_badge = outcome.get("badge") or "نتیجه پروژه"
    outcome_heading = outcome.get("heading") or "خروجی پروژه"
    outcome_body = outcome.get("body") or ""

    meta_html = "\n          ".join(
        [
            _meta_item("مشتری", client),
            _meta_item("نوع پروژه", project.get("industry") or ""),
            _meta_item("خدمات", project.get("services") or ""),
            _meta_item("نقش Hash Studio", role),
            _meta_item("پلتفرم", platform),
            _meta_item("سال", project.get("year") or ""),
            _meta_item("مدت", project.get("duration") or ""),
        ]
    )

    return f"""<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{escape_html(page_desc)}">
  <meta name="robots" content="index,follow">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="article">
  <meta property="og:locale" content="fa_IR">
  <meta property="og:site_name" content="استودیو هش">
  <meta property="og:title" content="{escape_html(page_title)}">
  <meta property="og:description" content="{escape_html(page_desc)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{og_image}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape_html(page_title)}">
  <meta name="twitter:description" content="{escape_html(page_desc)}">
  <meta name="twitter:image" content="{og_image}">
  <link rel="preload" as="image" href="{_attr(hero_src)}">
  <title>{escape_html(page_title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;700;800&display=swap" id="hash-font-vazirmatn">
  <link rel="icon" href="assets/images/home/logo.png" type="image/png">
  <link rel="stylesheet" href="css/tokens.css">
  <link rel="stylesheet" href="css/reset.css">
  <link rel="stylesheet" href="css/base.css">
  <link rel="stylesheet" href="css/home.css">
  <link rel="stylesheet" href="css/project.css">
  <script type="application/ld+json" id="project-jsonld">{ld}</script>
</head>
<body class="home-page project-page" data-slug="{_attr(slug)}">
{GENERATED_BANNER}

  <div class="top-bar">
    <div class="container top-bar__inner">
      <p class="top-bar__text">برای شروع پروژه جدید آماده‌ایم — درباره ایده‌تان با ما صحبت کنید</p>
      <a href="contact.html" class="top-bar__btn">شروع پروژه</a>
    </div>
  </div>

  <header class="home-header" id="site-header">
    <div class="container home-header__inner">
      <a href="index.html" class="home-header__logo">
        <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
        <span class="home-header__logo-text">استودیو هش</span>
      </a>

      <nav class="home-header__nav" id="main-nav" aria-label="منوی اصلی">
        <a href="index.html" class="home-header__link">خانه</a>
        <a href="services.html" class="home-header__link">خدمات</a>
        <a href="projects.html" class="home-header__link is-active">پروژه‌ها</a>
        <a href="about.html" class="home-header__link">درباره ما</a>
        <a href="blog.html" class="home-header__link">بلاگ</a>
        <a href="contact.html" class="home-header__link">تماس با ما</a>
      </nav>

      <div class="home-header__actions">
        <a href="contact.html" class="btn btn--primary btn--header">شروع پروژه</a>
        <a href="contact.html" class="home-header__profile" aria-label="تماس با ما">
          <img src="assets/icons/profile.svg" alt="" width="39" height="39">
        </a>
        <button class="home-header__toggle" aria-label="باز کردن منو" aria-expanded="false" aria-controls="main-nav">
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </div>
  </header>

    <div class="pd-progress" aria-hidden="true"><span class="pd-progress__bar" data-pd-progress></span></div>
    <nav class="pd-toc" aria-label="فهرست کیس‌استادی" data-pd-toc{_hidden(show_toc)}>
      <div class="container pd-toc__inner">
        <p class="pd-toc__label">مسیر مطالعه</p>
        <ul class="pd-toc__list" data-list="toc">
{toc_html}
        </ul>
      </div>
    </nav>

  <main id="project-root">
    <section class="pd-hero" id="pd-intro" data-toc="مقدمه">
      <div class="container">
        <div class="pd-hero__intro">
          <nav class="pd-breadcrumb" aria-label="مسیر">
            <a href="index.html">خانه</a>
            <span class="pd-breadcrumb__sep" aria-hidden="true">‹</span>
            <a href="projects.html">پروژه‌ها</a>
            <span class="pd-breadcrumb__sep" aria-hidden="true">‹</span>
            <span>{escape_html(name)}</span>
          </nav>
          <p class="pd-hero__brand">{escape_html(name)}</p>
          <div class="pd-hero__chips" aria-label="دسته‌بندی پروژه">
            <span class="pd-hero__chip">{escape_html(project.get("industry") or "")}</span>
            <span class="pd-hero__chip">{escape_html(project.get("services") or "")}</span>
          </div>
          <h1 class="pd-hero__title">{escape_html(title)}</h1>
          <p class="pd-hero__lead">{escape_html(lead)}</p>
          <p class="pd-hero__role">نقش استودیو هش: {escape_html(project.get("services") or "طراحی و توسعه محصول")}</p>
          <div class="pd-hero__actions">
            {live_btn}
            <a class="btn btn--outline btn--lg" href="contact.html" data-cta="start-project" data-cta-location="project-hero" data-project-slug="{_attr(slug)}">شروع پروژه</a>
          </div>
        </div>
        <figure class="pd-hero__media">
          <img src="{_attr(hero_src)}" alt="{_attr(f'نمای اصلی {name}')}" width="1280" height="720" loading="eager" fetchpriority="high" decoding="async">
        </figure>
      </div>
    </section>

    <section class="pd-meta" id="pd-meta" aria-label="اطلاعات پروژه">
      <div class="container">
        <dl class="pd-meta__grid">
          {meta_html}
        </dl>
      </div>
    </section>

    <section class="pd-section pd-section--cream" id="pd-summary" data-block="summary" data-toc="خلاصه"{_hidden(show_summary)}>
      <div class="container pd-split">
        <div class="pd-split__copy">
          <span class="badge badge--section">{escape_html(summary.get("badge") or "")}</span>
          <h2 class="pd-section__title">{escape_html(summary.get("heading") or "")}</h2>
          <p class="pd-section__body">{escape_html(summary.get("body") or "")}</p>
        </div>
        <div data-block="early-metrics"{_hidden(show_early)}><p class="pd-early__caption">اعداد محصول — از خود پروژه، نه KPI استودیو</p><ul class="pd-early" data-list="earlyMetrics">{early_html}</ul></div>
      </div>
    </section>

    <section class="pd-section pd-section--white" id="pd-challenge" data-block="challenge" data-toc="چالش"{_hidden(show_challenge)}>
      <div class="container pd-split pd-split--visual">
        <figure class="pd-split__media pd-split__media--tall">
          <img src="{_attr(challenge_img)}" alt="{_attr(f'فضای محصول {name}')}" width="960" height="1280" loading="lazy" decoding="async">
        </figure>
        <div class="pd-split__copy">
          <span class="badge badge--section">مسئله چه بود؟</span>
          <h2 class="pd-section__title">{escape_html(challenge.get("heading") or "")}</h2>
          <p class="pd-section__body">{escape_html(challenge.get("body") or "")}</p>
          <h3 class="pd-section__sub">اهداف استراتژیک</h3>
          <ul class="pd-goals" data-list="goals">{goals_html}</ul>
        </div>
      </div>
    </section>

    <section class="pd-section pd-section--cream" id="pd-research" data-block="research" data-toc="تحقیق"{_hidden(show_research)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">رویکرد ما</span>
          <h2 class="section-head__title">از کشف مسئله تا مسیر محصول</h2>
          <p class="section-head__desc">استراتژی، تحقیق و طراحی تجربه — بر اساس واقعیت‌های کاربر و محدودیت‌های کسب‌وکار.</p>
        </div>
      </div>
      <div class="container pd-split pd-split--visual pd-split--flip" style="margin-top:2.5rem">
        <div class="pd-split__copy">
          <span class="badge badge--section">تحقیق و استراتژی</span>
          <h2 class="pd-section__title">{escape_html(research.get("heading") or "")}</h2>
          <p class="pd-section__body">{escape_html(research.get("sub") or "")}</p>
          <h3 class="pd-section__sub">یافته‌های کلیدی</h3>
          <ul class="pd-findings" data-list="findings">{findings_html}</ul>
        </div>
        <figure class="pd-split__media">
          <img src="{_attr(research_img)}" alt="{_attr(f'جزئیات تجربه {name}')}" width="1280" height="720" loading="lazy" decoding="async">
        </figure>
      </div>
      <div class="container" style="margin-top:3rem">
        <figure class="pd-feature">
          <img src="{_attr(feature_src)}" alt="{_attr(feature_alt)}" width="1600" height="686" loading="lazy" decoding="async">
        </figure>
      </div>
    </section>

    <section class="pd-section pd-section--white" id="pd-ux" data-block="ux" data-toc="تجربه کاربری"{_hidden(show_ux)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">UX و محصول</span>
          <h2 class="section-head__title">{escape_html(ux.get("heading") or "")}</h2>
        </div>
        <div class="pd-ux" data-list="ux">{ux_html}</div>
      </div>
    </section>

    <section class="pd-section pd-section--cream" id="pd-design" data-block="ds" data-toc="طراحی"{_hidden(show_ds)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">جزئیات رابط</span>
          <h2 class="section-head__title">{escape_html(design_system.get("heading") or "")}</h2>
          <p class="section-head__desc">{escape_html(design_system.get("body") or "")}</p>
        </div>
        <div class="pd-ds">{ds_html}</div>
      </div>
    </section>

    <section class="pd-section pd-section--white" id="pd-gallery" data-block="gallery" data-toc="گالری"{_hidden(show_gallery)}>
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">تجربه محصول</span>
          <h2 class="section-head__title">صفحاتی از تجربه نهایی</h2>
          <p class="section-head__desc">نمایی از رابط واقعی — بزرگ، خوانا و نزدیک به تجربه کاربر.</p>
        </div>
        <div class="pd-gallery" data-list="gallery">{gallery_html}</div>
      </div>
    </section>

    <section class="pd-section pd-section--cream" id="pd-tech" data-block="tech" data-toc="فناوری"{_hidden(show_tech)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">پیاده‌سازی فنی</span>
          <h2 class="section-head__title">{escape_html(tech.get("heading") or "")}</h2>
          <p class="section-head__desc">{escape_html(tech.get("body") or "")}</p>
        </div>
        <div class="pd-arch" aria-label="معماری فنی سیستم">
          <p class="pd-arch__caption">چگونه ساختیم</p>
          <ol class="pd-arch__layers" data-list="layers">{layers_html}</ol>
        </div>
        <ul class="pd-stack" data-list="stack">{stack_html}</ul>
      </div>
    </section>

    <section class="pd-section pd-section--white" id="pd-outcome" data-block="outcome" data-toc="نتیجه"{_hidden(show_outcome)}>
      <div class="container">
        <div class="pd-outcome-head" data-block="outcome-copy"{_hidden(bool(outcome.get("body")))}>
          <span class="badge badge--section">{escape_html(outcome_badge)}</span>
          <h2 class="pd-section__title">{escape_html(outcome_heading)}</h2>
          <p class="pd-section__body">{escape_html(outcome_body)}</p>
        </div>
        <p class="pd-outcome__caption">نشانه‌های محصول و خروجی طراحی — نه شاخص مالی تأییدنشده</p>
        <ul class="pd-kpis" data-list="kpis">{kpis_html}</ul>
      </div>
    </section>

    <section class="pd-section pd-section--cream" data-block="quote"{_hidden(show_quote)}>
      <div class="container">
        <blockquote class="pd-quote">
          <p class="pd-quote__eyebrow">درس محصول از این پروژه</p>
          <p class="pd-quote__text">{escape_html(quote.get("text") or "")}</p>
          <footer class="pd-quote__footer">
            <div>
              <cite class="pd-quote__role">{escape_html(quote.get("role") or "")}</cite>
              <span class="pd-quote__org">{escape_html(quote.get("org") or "")}</span>
            </div>
          </footer>
        </blockquote>
      </div>
    </section>

    <section class="pd-section pd-section--dark" data-block="closing"{_hidden(show_closing)}>
      <div class="container">
        <article class="pd-closing">
          <h2 class="pd-closing__title">{escape_html(closing.get("heading") or "")}</h2>
          <p class="pd-closing__body">{escape_html(closing.get("body") or "")}</p>
        </article>
      </div>
    </section>

    <section class="pd-section pd-section--cream" data-block="service-links"{_hidden(show_services)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">خدمات مرتبط</span>
          <h2 class="section-head__title">این پروژه با کدام قابلیت‌های استودیو ساخته شد؟</h2>
        </div>
        <div class="pd-service-links" data-list="service-links">{service_links_html}</div>
      </div>
    </section>

    <section class="home-final-cta">
      <div class="container">
        <article class="home-final-cta__card">
          <h2 class="home-final-cta__title">اگر مسئله‌ای شبیه {escape_html(name)} دارید</h2>
          <p class="home-final-cta__desc">از {escape_html(project.get("industry") or "مسئله محصول")} تا {escape_html(project.get("services") or "طراحی و توسعه")} — درباره گلوگاه واقعی‌تان حرف بزنیم. بریف کامل لازم نیست.</p>
          <div class="home-final-cta__actions">
            <a href="contact.html" class="btn btn--primary btn--lg" data-cta="start-project" data-cta-location="project-cta" data-project-slug="{_attr(slug)}">شروع پروژه</a>
            <a href="projects.html" class="btn btn--outline btn--lg" data-cta="view-projects" data-cta-location="project-cta">بازگشت به پروژه‌ها</a>
          </div>
        </article>
      </div>
    </section>

    <section class="pd-section pd-section--cream" data-block="project-articles"{_hidden(show_articles)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">از نگاه استودیو هش</span>
          <h2 class="section-head__title">مقالاتی مرتبط با این مسئله</h2>
        </div>
        <div class="pd-articles" data-list="project-articles">{"".join(article_cards)}</div>
      </div>
    </section>

    <section class="pd-related" data-block="related"{_hidden(show_related)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">پروژه‌های دیگر</span>
          <h2 class="section-head__title">نمونه‌های دیگر استودیو هش</h2>
        </div>
        <div class="pd-related__grid" data-list="related">{related_html}</div>
      </div>
    </section>

    <nav class="pd-pager" aria-label="ناوبری پروژه‌ها">
      <div class="container pd-pager__inner">
        <a class="pd-pager__link pd-pager__link--prev" href="{prev_href}"{_hidden(bool(prev))} data-cta="view-project" data-cta-location="project-pager" data-project-slug="{_attr(prev["slug"]) if prev else ""}">
          <span class="pd-pager__dir">← پروژه قبلی</span>
          <span class="pd-pager__name">{escape_html(prev_name or "")}</span>
        </a>
        <a class="pd-pager__home" href="projects.html" data-cta="view-projects" data-cta-location="project-pager">همه پروژه‌ها</a>
        <a class="pd-pager__link pd-pager__link--next" href="{next_href}" data-cta="view-project" data-cta-location="project-pager" data-project-slug="{_attr(nxt["slug"]) if nxt else ""}">
          <span class="pd-pager__dir">پروژه بعدی →</span>
          <span class="pd-pager__name">{escape_html(next_name or "")}</span>
        </a>
      </div>
    </nav>

    <section class="pd-next" data-block="next"{_hidden(show_next)}>
      <div class="container">
        <a class="pd-next__card" href="{next_href}" data-cta="view-project" data-cta-location="project-next" data-project-slug="{_attr(nxt["slug"]) if nxt else ""}">
          <div class="pd-next__copy">
            <span class="pd-next__label">پروژه بعدی</span>
            <span class="pd-next__pill">{escape_html(next_industry or "")}</span>
            <h2 class="pd-next__title">{escape_html(next_name or "")}</h2>
            <p class="pd-next__desc">{escape_html(next_lead or "")}</p>
          </div>
          <figure class="pd-next__media">
            <img src="{_attr(next_img)}" alt="{_attr(next_name or "")}" width="640" height="360" loading="lazy" decoding="async">
          </figure>
        </a>
      </div>
    </section>
  </main>

  <footer class="home-footer">
    <div class="container">
      <div class="home-footer__grid">
        <div class="home-footer__brand">
          <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
          <div class="home-footer__brand-name">استودیو هش</div>
          <p class="home-footer__brand-desc">طراحی و توسعه محصولات دیجیتال برای استارتاپ‌ها و شرکت‌های پیشرو — از ایده تا تجربه‌ای که کاربران عاشقش می‌شوند.</p>
          <div class="home-footer__location">
            <span class="home-footer__location-icon" aria-hidden="true">📍</span>
            <span data-studio="address-short">تهران، یوسف‌آباد، جهان‌آرا، کوچه ۴۳</span>
          </div>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">دسترسی سریع</h3>
          <nav class="home-footer__links" aria-label="لینک‌های فوتر">
            <a href="index.html" class="home-footer__link">خانه اصلی</a>
            <a href="services.html" class="home-footer__link">خدمات</a>
            <a href="projects.html" class="home-footer__link">پروژه‌ها و نمونه‌کارها</a>
            <a href="about.html" class="home-footer__link">درباره ما</a>
            <a href="blog.html" class="home-footer__link">وبلاگ تخصصی</a>
            <a href="contact.html" class="home-footer__link">تماس با ما</a>
          </nav>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">خدمات ما</h3>
          <nav class="home-footer__links">
            <a href="/service/product/" class="home-footer__link">طراحی محصول</a>
            <a href="/service/ui-ux/" class="home-footer__link">طراحی UI/UX</a>
            <a href="/service/web/" class="home-footer__link">توسعه وب مدرن</a>
            <a href="/service/mobile/" class="home-footer__link">توسعه اپلیکیشن موبایل</a>
            <a href="/service/mvp/" class="home-footer__link">راه‌اندازی MVP</a>
            <a href="/service/ai/" class="home-footer__link">یکپارچه‌سازی هوش مصنوعی</a>
            <a href="/service/seo/" class="home-footer__link">سئو و رشد</a>
            <a href="/service/consulting/" class="home-footer__link">مشاوره محصول</a>
          </nav>
        </div>
        <div class="home-footer__newsletter-col">
          <h3 class="home-footer__heading">پروژه بعدی شما</h3>
          <p class="home-footer__newsletter-desc">ایده، محصول نیمه‌کاره یا بازطراحی — مسیر را با هم مشخص می‌کنیم.</p>
          <a class="btn btn--primary" href="/contact.html" data-cta="start-project" data-cta-location="footer">شروع پروژه</a>
          <div class="home-footer__social" data-studio="social" data-studio-social-class="home-footer__social-link">
            <a href="https://www.instagram.com/hashstudio.ir/" class="home-footer__social-link" aria-label="اینستاگرام" target="_blank" rel="noopener noreferrer">IG</a>
          </div>
        </div>
      </div>
      <div class="home-footer__bottom">
        <span>تمامی حقوق مادی و معنوی محفوظ است © ۱۴۰۵ استودیو هش</span>
        <span>طراحی و توسعه با ■ در استودیو هش</span>
      </div>
    </div>
  </footer>

  <script src="js/project.js"></script>
  <script src="js/main.js"></script>
  <script src="/js/studio-info.js"></script>
  <script src="/js/analytics.js"></script>
  <script src="/js/studio-chrome.js"></script>
</body>
</html>
"""


def generate_projects(data: dict[str, Any], root: Path) -> int:
    projects = data.get("projects") or []
    if not projects:
        raise RuntimeError("site-data.json has zero projects — refusing to generate")
    articles = data.get("articles") or {}
    graph_projects = (data.get("graph") or {}).get("projects") or {}
    written = 0
    for project in projects:
        slug = project.get("slug")
        if not slug:
            continue
        html = render_project(project, projects, articles, graph_projects)
        out_dir = root / "project" / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(html, encoding="utf-8")
        written += 1
    if written == 0:
        raise RuntimeError("No project pages were written")
    return written
