#!/usr/bin/env python3
"""Static HTML renderer for high-intent /solutions/<slug>/ proposal pages."""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from hash_content import BASE, SERVICE_LABELS, abs_url, escape_html, service_url

GENERATED_BANNER = (
    "<!-- Generated by scripts/build-high-intent.py — do not edit by hand. "
    "Source: js/high-intent-data.js -->"
)

ROOT = Path(__file__).resolve().parents[1]


def solutions_url(slug: str) -> str:
    return f"{BASE}/solutions/{slug}/"


# Backward-compatible alias (older call sites / docs)
def for_url(slug: str) -> str:
    return solutions_url(slug)


def load_high_intent_pages() -> list[dict[str, Any]]:
    result = __import__("subprocess").run(
        [
            "node",
            "-e",
            "const fs=require('fs');"
            "const vm=require('vm');"
            "const src=fs.readFileSync('js/high-intent-data.js','utf8');"
            "const s={};vm.runInNewContext(src,s);"
            "process.stdout.write(JSON.stringify(s.HASH_HIGH_INTENT_PAGES));",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to load high-intent data: {result.stderr}")
    data = json.loads(result.stdout)
    if not isinstance(data, list) or not data:
        raise RuntimeError("HASH_HIGH_INTENT_PAGES empty")
    return data


def _attr(value: Any) -> str:
    return escape_html(value)


def _json_ld(page: dict[str, Any], canonical: str, page_desc: str) -> str:
    name = page.get("name") or ""
    primary = page.get("primaryService") or ""
    graph: list[dict[str, Any]] = [
        {
            "@type": "WebPage",
            "name": name,
            "description": page_desc,
            "url": canonical,
            "inLanguage": "fa-IR",
            "isPartOf": {"@type": "WebSite", "name": "استودیو هش", "url": f"{BASE}/"},
        },
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "خانه", "item": f"{BASE}/"},
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "خدمات",
                    "item": f"{BASE}/services.html",
                },
                {"@type": "ListItem", "position": 3, "name": name, "item": canonical},
            ],
        },
    ]
    if primary:
        graph[0]["about"] = {
            "@type": "Service",
            "name": SERVICE_LABELS.get(primary, primary),
            "url": service_url(primary),
        }
    faqs = page.get("faqs") or []
    if faqs:
        graph.append(
            {
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": item.get("q") or "",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": item.get("a") or "",
                        },
                    }
                    for item in faqs
                    if item.get("q") and item.get("a")
                ],
            }
        )
    return json.dumps(
        {"@context": "https://schema.org", "@graph": graph},
        ensure_ascii=False,
        separators=(",", ":"),
    )


def _project_entries(page: dict[str, Any]) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for item in page.get("projects") or []:
        if isinstance(item, str):
            entries.append({"slug": item, "why": ""})
        elif isinstance(item, dict) and item.get("slug"):
            entries.append(
                {
                    "slug": str(item["slug"]),
                    "why": str(item.get("why") or "").strip(),
                }
            )
    return entries


def _project_card(
    slug: str,
    projects_by: dict[str, dict[str, Any]],
    intent: str,
    primary_service: str,
    why: str = "",
) -> str:
    live = projects_by.get(slug) or {}
    name = live.get("name") or slug
    meta = " · ".join(x for x in [live.get("industry"), live.get("services")] if x)
    title = name
    if live.get("lead"):
        title = f"{name} — {(live.get('lead') or '').split('،')[0]}"
    shot = f"assets/images/home/projects/{slug}-shot.webp"
    if slug == "moniaz":
        shot = f"assets/images/home/projects/{slug}-s1.webp"
    pixel = f"assets/images/home/projects/{slug}-pixel.webp"
    why_html = (
        f'<p class="hi-case__why"><span class="hi-case__why-label">چرا مرتبط است:</span> '
        f"{escape_html(why)}</p>"
        if why
        else ""
    )
    return (
        f'<a class="sd-case" href="/project/{_attr(slug)}/" '
        f'data-cta="high-intent-project" data-cta-location="high-intent-page" '
        f'data-project-slug="{_attr(slug)}" data-fit-intent="{_attr(intent)}" '
        f'data-service-slug="{_attr(primary_service)}">'
        f'<div class="sd-case__media"><div class="site-preview">'
        f'<div class="site-preview__pixel" aria-hidden="true">'
        f'<img src="{_attr(pixel)}" alt="{_attr(name)}" width="1280" height="720" loading="lazy"></div>'
        f'<img class="site-preview__shot" src="{_attr(shot)}" alt="" width="1280" height="720" '
        f'loading="lazy" aria-hidden="true"></div></div>'
        f'<div class="sd-case__body">'
        f'<div class="sd-case__meta">{escape_html(meta)}</div>'
        f'<h3 class="sd-case__title">{escape_html(title)}</h3>'
        f"{why_html}"
        f'<span class="sd-case__cta">مطالعه تجربه {escape_html(name)}</span>'
        f"</div></a>"
    )


def render_high_intent(
    page: dict[str, Any],
    projects_by: dict[str, dict[str, Any]],
    articles_by: dict[str, dict[str, Any]],
) -> str:
    slug = page["slug"]
    name = page.get("name") or ""
    seo = page.get("seo") or {}
    hero = page.get("hero") or {}
    primary = page.get("primaryService") or ""
    page_title = (seo.get("title") or "").strip() or f"{name} | استودیو هش"
    page_desc = (seo.get("description") or "").strip() or (hero.get("lead") or "")
    canonical = solutions_url(slug)
    theme = page.get("theme") or "product"
    contact_href = (
        f"contact.html?service={_attr(primary)}&intent={_attr(slug)}"
        if primary
        else "contact.html"
    )
    project_entries = _project_entries(page)
    first_project = project_entries[0]["slug"] if project_entries else None
    hero_image = (
        f"assets/images/home/projects/{first_project}-shot.webp"
        if first_project
        else "assets/images/home/logo.png"
    )
    if first_project == "moniaz":
        hero_image = "assets/images/home/projects/moniaz-s1.webp"
    og_image = abs_url(hero_image)
    ld = _json_ld(page, canonical, page_desc)
    cta_label = (page.get("cta") or {}).get("primary") or "شروع یک پروژه"

    situation = page.get("situation") or {}
    sit_points = "".join(
        f"<li>{escape_html(p)}</li>" for p in (situation.get("points") or [])
    )
    fit = page.get("fitFor") or {}
    fit_html = "".join(
        f'<li class="sd-fit__item">{escape_html(item)}</li>'
        for item in (fit.get("items") or [])
    )
    fit_not = page.get("fitNotFor") or {}
    fit_not_html = "".join(
        f'<li class="sd-fit__item sd-fit__item--not">{escape_html(item)}</li>'
        for item in (fit_not.get("items") or [])
    )
    approach = page.get("approach") or {}
    approach_items = "".join(
        f"<li>{escape_html(item)}</li>" for item in (approach.get("items") or [])
    )
    deliverables = page.get("deliverables") or {}
    deliv_html = "".join(
        f"<li>{escape_html(item)}</li>" for item in (deliverables.get("items") or [])
    )
    process = page.get("process") or {}
    steps_html = "".join(
        f'<li class="sd-step"><div class="sd-step__num">{escape_html(s.get("num") or "")}</div>'
        f'<h3 class="sd-step__title">{escape_html(s.get("title") or "")}</h3>'
        f'<p class="sd-step__desc">{escape_html(s.get("desc") or "")}</p></li>'
        for s in (process.get("steps") or [])
    )
    outcomes = page.get("outcomes") or {}
    outcomes_html = "".join(
        f'<li class="hi-outcome">{escape_html(item)}</li>'
        for item in (outcomes.get("items") or [])
    )
    cases_html = "".join(
        _project_card(entry["slug"], projects_by, slug, primary, entry.get("why") or "")
        for entry in project_entries
    )

    article_cards: list[str] = []
    for aslug in page.get("articles") or []:
        a = articles_by.get(aslug)
        if not a:
            continue
        article_cards.append(
            f'<a class="sd-article" href="/article/{_attr(aslug)}/" '
            f'data-cta="view-article" data-cta-location="high-intent-page" '
            f'data-content-slug="{_attr(aslug)}" data-fit-intent="{_attr(slug)}" '
            f'data-service-slug="{_attr(primary)}">'
            f'<span class="sd-article__tag">{escape_html(a.get("tag") or "")}</span>'
            f'<h3 class="sd-article__title">{escape_html(a.get("title") or "")}</h3>'
            f'<p class="sd-article__lead">{escape_html((a.get("lead") or "")[:140])}</p>'
            f'<span class="sd-article__cta">خواندن مقاله</span></a>'
        )

    related_svc = "".join(
        f'<a class="hi-related__link" href="/service/{_attr(s)}/" '
        f'data-cta="view-service" data-cta-location="high-intent-page" '
        f'data-service-slug="{_attr(s)}" data-fit-intent="{_attr(slug)}">'
        f"{escape_html(SERVICE_LABELS.get(s, s))}</a>"
        for s in (page.get("relatedServices") or [])
        if s in SERVICE_LABELS
    )
    primary_label = SERVICE_LABELS.get(primary, primary)
    faqs_html = "".join(
        f'<details class="faq-item"{" open" if i == 0 else ""}>'
        f'<summary class="faq-item__question"><span class="faq-item__label">'
        f'{escape_html(item.get("q") or "")}</span>'
        f'<span class="faq-item__icon" aria-hidden="true"></span></summary>'
        f'<p class="faq-item__answer">{escape_html(item.get("a") or "")}</p></details>'
        for i, item in enumerate(page.get("faqs") or [])
    )
    cta = page.get("cta") or {}

    return f"""<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{escape_html(page_desc)}">
  <meta name="robots" content="index,follow">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="fa_IR">
  <meta property="og:site_name" content="استودیو هش">
  <meta property="og:title" content="{escape_html(page_title)}">
  <meta property="og:description" content="{escape_html(page_desc)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{og_image}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape_html(page_title)}">
  <meta name="twitter:description" content="{escape_html(page_desc)}">
  <meta name="twitter:image" content="{og_image}">
  <title>{escape_html(page_title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;700;800&display=swap" id="hash-font-vazirmatn">
  <link rel="icon" href="assets/images/home/logo.png" type="image/png">
  <link rel="stylesheet" href="css/tokens.css">
  <link rel="stylesheet" href="css/reset.css">
  <link rel="stylesheet" href="css/base.css">
  <link rel="stylesheet" href="css/home.css">
  <link rel="stylesheet" href="css/services.css">
  <link rel="stylesheet" href="css/service-detail.css">
  <link rel="stylesheet" href="css/high-intent.css">
  <script type="application/ld+json" id="high-intent-jsonld">{ld}</script>
</head>
<body class="home-page sd-page hi-page" data-slug="{_attr(slug)}" data-theme="{_attr(theme)}" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-page-type="high-intent">
{GENERATED_BANNER}

  <a class="skip-link" href="#hi-root">رفتن به محتوای اصلی</a>

  <div class="top-bar">
    <div class="container top-bar__inner">
      <p class="top-bar__text">برای شروع پروژه جدید آماده‌ایم — درباره ایده‌تان با ما صحبت کنید</p>
      <a href="{contact_href}" class="top-bar__btn" data-cta="high-intent-cta" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-recommended-service="{_attr(primary)}">{escape_html(cta_label)}</a>
    </div>
  </div>

  <header class="home-header" id="site-header">
    <div class="container home-header__inner">
      <a href="index.html" class="home-header__logo">
        <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
        <span class="home-header__logo-text">استودیو هش</span>
      </a>
      <nav class="home-header__nav" id="main-nav" aria-label="منوی اصلی">
        <a href="index.html" class="home-header__link">خانه</a>
        <a href="services.html" class="home-header__link">خدمات</a>
        <a href="projects.html" class="home-header__link">پروژه‌ها</a>
        <a href="about.html" class="home-header__link">درباره ما</a>
        <a href="blog.html" class="home-header__link">بلاگ</a>
        <a href="contact.html" class="home-header__link">تماس با ما</a>
      </nav>
      <div class="home-header__actions">
        <a href="{contact_href}" class="btn btn--primary btn--header" data-cta="high-intent-cta" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-recommended-service="{_attr(primary)}">{escape_html(cta_label)}</a>
        <button class="home-header__toggle" aria-label="باز کردن منو" aria-expanded="false" aria-controls="main-nav">
          <span></span><span></span><span></span>
        </button>
      </div>
    </div>
  </header>

  <main id="hi-root">
    <section class="sd-hero">
      <div class="container sd-hero__grid">
        <div class="sd-hero__copy">
          <nav class="sd-breadcrumb" aria-label="مسیر">
            <a href="index.html">خانه</a>
            <span class="sd-breadcrumb__sep" aria-hidden="true">‹</span>
            <a href="services.html">خدمات</a>
            <span class="sd-breadcrumb__sep" aria-hidden="true">‹</span>
            <span class="sd-breadcrumb__current">{escape_html(name)}</span>
          </nav>
          <span class="badge badge--section">{escape_html(hero.get("badge") or "")}</span>
          <h1 class="sd-hero__title">
            <span>{escape_html(hero.get("titleLead") or name)}</span>
            <span class="sd-hero__accent">{escape_html(hero.get("titleAccent") or "")}</span>
          </h1>
          <p class="sd-hero__lead">{escape_html(hero.get("lead") or page_desc)}</p>
          <div class="sd-hero__actions">
            <a href="{contact_href}" class="btn btn--primary btn--lg" data-cta="high-intent-cta" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-recommended-service="{_attr(primary)}">{escape_html(cta_label)}</a>
            <a href="#cases" class="btn btn--outline btn--lg">دیدن نمونه‌کارهای مرتبط</a>
          </div>
        </div>
        <figure class="sd-hero__media">
          <img src="{_attr(hero_image)}" alt="{escape_html(name)}" width="540" height="380" loading="eager" fetchpriority="high" decoding="async">
        </figure>
      </div>
    </section>

    <section class="sd-section">
      <div class="container hi-block">
        <div class="section-head section-head--start">
          <span class="badge badge--section">موقعیت</span>
          <h2 class="section-head__title">{escape_html(situation.get("title") or "")}</h2>
        </div>
        <p class="hi-prose">{escape_html(situation.get("body") or "")}</p>
        <ul class="hi-bullets">{sit_points}</ul>
      </div>
    </section>

    <section class="sd-section sd-section--cream">
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">تناسب</span>
          <h2 class="section-head__title">چه کسی باید (و نباید) این مسیر را انتخاب کند؟</h2>
        </div>
        <div class="hi-fit-grid">
          <div class="hi-fit-col">
            <h3 class="hi-fit-col__title">{escape_html(fit.get("title") or "مناسب است")}</h3>
            <ul class="sd-fit">{fit_html}</ul>
          </div>
          <div class="hi-fit-col hi-fit-col--not">
            <h3 class="hi-fit-col__title">{escape_html(fit_not.get("title") or "معمولاً مناسب نیست")}</h3>
            <ul class="sd-fit">{fit_not_html}</ul>
          </div>
        </div>
        <p class="hi-fit-guide">اگر هنوز مطمئن نیستید این مسیر برای شما مناسب است، <a href="/#service-fit" data-cta="service-fit-guide" data-cta-location="high-intent-page" data-fit-intent="{_attr(slug)}" data-service-slug="{_attr(primary)}">مسیر مناسب را پیدا کنید</a>.</p>
      </div>
    </section>

    <section class="sd-section sd-section--white">
      <div class="container hi-block">
        <div class="section-head section-head--start">
          <span class="badge badge--section">رویکرد استودیو</span>
          <h2 class="section-head__title">{escape_html(approach.get("title") or "")}</h2>
        </div>
        <p class="hi-prose">{escape_html(approach.get("body") or "")}</p>
        <ul class="sd-checks">{approach_items}</ul>
      </div>
    </section>

    <section class="sd-section">
      <div class="container sd-split">
        <div class="sd-panel">
          <h2 class="sd-panel__title">{escape_html(deliverables.get("title") or "")}</h2>
          <p class="sd-panel__sub">{escape_html(deliverables.get("sub") or "")}</p>
          <ul class="sd-checks">{deliv_html}</ul>
        </div>
        <div class="sd-panel">
          <h2 class="sd-panel__title">{escape_html(outcomes.get("title") or "")}</h2>
          <p class="sd-panel__sub">بدون وعده عدد جعلی — هدف‌های قابل‌سنجش بعد از کشف دامنه دقیق می‌شوند.</p>
          <ul class="hi-outcomes">{outcomes_html}</ul>
        </div>
      </div>
    </section>

    <section class="sd-section sd-section--white">
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">{escape_html(process.get("badge") or "")}</span>
          <h2 class="section-head__title">{escape_html(process.get("title") or "")}</h2>
        </div>
        <ol class="sd-steps">{steps_html}</ol>
      </div>
    </section>

    <section class="sd-section" id="cases">
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">شواهد واقعی</span>
          <h2 class="section-head__title">نمونه‌کارهای نزدیک به این مسئله</h2>
        </div>
        <div class="sd-cases">{cases_html}</div>
      </div>
    </section>

    <section class="sd-section sd-section--cream">
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">خدمات مرتبط</span>
          <h2 class="section-head__title">از این مسیر به کدام خدمت وصل می‌شوید؟</h2>
        </div>
        <p class="hi-prose">خدمت اصلی پیشنهادی: <a href="{service_url(primary).replace(BASE, '')}" data-cta="view-service" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}">{escape_html(primary_label)}</a></p>
        <div class="hi-related">{related_svc}</div>
      </div>
    </section>

    <section class="sd-section sd-section--white"{"" if article_cards else " hidden"}>
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">مطالعه بیشتر</span>
          <h2 class="section-head__title">مقالات مرتبط</h2>
        </div>
        <div class="sd-articles">{"".join(article_cards)}</div>
      </div>
    </section>

    <section class="sd-section">
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">سؤال‌های رایج</span>
          <h2 class="section-head__title">قبل از تماس معمولاً این‌ها را می‌پرسند</h2>
        </div>
        <div class="faq-list sd-faq">{faqs_html}</div>
      </div>
    </section>

    <section class="home-final-cta">
      <div class="container">
        <article class="home-final-cta__card">
          <h2 class="home-final-cta__title">{escape_html(cta.get("title") or "")}</h2>
          <p class="home-final-cta__desc">{escape_html(cta.get("body") or "")}</p>
          <div class="home-final-cta__actions">
            <a href="{contact_href}" class="btn btn--primary btn--lg" data-cta="high-intent-cta" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-recommended-service="{_attr(primary)}">{escape_html(cta_label)}</a>
            <a href="/service/{_attr(primary)}/" class="btn btn--outline btn--lg" data-cta="view-service" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}">مشاهده خدمت {escape_html(primary_label)}</a>
          </div>
        </article>
      </div>
    </section>
  </main>

  <footer class="home-footer">
    <div class="container">
      <div class="home-footer__grid">
        <div class="home-footer__brand">
          <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
          <div class="home-footer__brand-name">استودیو هش</div>
          <p class="home-footer__brand-desc">طراحی و توسعه محصولات دیجیتال برای استارتاپ‌ها و شرکت‌های پیشرو — از ایده تا تجربه‌ای که کاربران عاشقش می‌شوند.</p>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">دسترسی سریع</h3>
          <nav class="home-footer__links" aria-label="لینک‌های فوتر">
            <a href="index.html" class="home-footer__link">خانه اصلی</a>
            <a href="services.html" class="home-footer__link">خدمات</a>
            <a href="projects.html" class="home-footer__link">پروژه‌ها و نمونه‌کارها</a>
            <a href="about.html" class="home-footer__link">درباره ما</a>
            <a href="blog.html" class="home-footer__link">وبلاگ تخصصی</a>
            <a href="contact.html" class="home-footer__link">تماس با ما</a>
          </nav>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">خدمات ما</h3>
          <nav class="home-footer__links">
            <a href="/service/product/" class="home-footer__link">طراحی محصول</a>
            <a href="/service/ui-ux/" class="home-footer__link">طراحی UI/UX</a>
            <a href="/service/web/" class="home-footer__link">توسعه وب مدرن</a>
            <a href="/service/mvp/" class="home-footer__link">راه‌اندازی MVP</a>
            <a href="/service/seo/" class="home-footer__link">سئو و رشد</a>
          </nav>
        </div>
        <div class="home-footer__newsletter-col">
          <h3 class="home-footer__heading">پروژه بعدی شما</h3>
          <p class="home-footer__newsletter-desc">ایده، محصول نیمه‌کاره یا بازطراحی — مسیر را با هم مشخص می‌کنیم.</p>
          <a class="btn btn--primary" href="{contact_href}" data-cta="high-intent-cta" data-cta-location="high-intent-page" data-service-slug="{_attr(primary)}" data-fit-intent="{_attr(slug)}" data-recommended-service="{_attr(primary)}">{escape_html(cta_label)}</a>
        </div>
      </div>
      <div class="home-footer__bottom">
        <span>تمامی حقوق مادی و معنوی محفوظ است © ۱۴۰۵ استودیو هش</span>
        <span>طراحی و توسعه با ■ در استودیو هش</span>
      </div>
    </div>
  </footer>

  <script src="js/main.js"></script>
  <script src="/js/studio-info.js"></script>
  <script src="/js/analytics.js"></script>
  <script src="/js/studio-chrome.js"></script>
</body>
</html>
"""


def generate_high_intent(root: Path) -> int:
    from hash_content import load_articles, load_project_cards

    pages = load_high_intent_pages()
    projects_by = load_project_cards()
    articles_by = load_articles()
    out_root = root / "solutions"
    legacy_for = root / "for"
    if out_root.exists():
        for child in out_root.iterdir():
            if child.is_dir():
                index = child / "index.html"
                if index.exists():
                    index.unlink()
                try:
                    child.rmdir()
                except OSError:
                    pass
    # Prefer /solutions/; drop legacy /for/ so sitemap/validators stay clean
    if legacy_for.exists():
        shutil.rmtree(legacy_for)
    written = 0
    for page in pages:
        slug = page["slug"]
        html = render_high_intent(page, projects_by, articles_by)
        dest = out_root / slug
        dest.mkdir(parents=True, exist_ok=True)
        (dest / "index.html").write_text(html, encoding="utf-8")
        written += 1
    return written
