#!/usr/bin/env python3
"""Static HTML renderer for service detail pages."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from hash_content import BASE, abs_url, escape_html, service_url

GENERATED_BANNER = (
    "<!-- Generated by scripts/build-services.py — do not edit by hand. "
    "Source: js/services-data.js -->"
)

PAIN_NUMS = ["۰۱", "۰۲", "۰۳", "۰۴"]


def _hidden(show: bool) -> str:
    return "" if show else " hidden"


def _attr(value: Any) -> str:
    return escape_html(value)


def _body_classes(svc: dict[str, Any]) -> str:
    classes = ["home-page", "sd-page"]
    if svc.get("heroFlip"):
        classes.append("is-hero-flip")
    if svc.get("statsLayout") == "row":
        classes.append("is-stats-row")
    if svc.get("painsLayout") == "stack":
        classes.append("is-pains-stack")
    if svc.get("stepsLayout") == "stack":
        classes.append("is-steps-stack")
    if svc.get("splitFlip"):
        classes.append("is-split-flip")
    tools_len = len(svc.get("tools") or [])
    if tools_len == 4:
        classes.append("is-tools-4")
    if tools_len >= 6:
        classes.append("is-tools-6")
    return " ".join(classes)


def resolve_cases(svc: dict[str, Any], projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_slug = {p["slug"]: p for p in projects}
    curated: list[dict[str, Any]] = []
    for item in svc.get("cases") or []:
        slug = item.get("slug")
        if not slug:
            continue
        live = by_slug.get(slug)
        if live:
            curated.append(
                {
                    "slug": slug,
                    "meta": item.get("meta")
                    or " • ".join(
                        x for x in [live.get("year"), live.get("industry")] if x
                    ),
                    "title": item.get("title") or live.get("name") or "",
                    "tags": item.get("tags") or (live.get("tags") or [])[:3],
                }
            )
        else:
            curated.append(
                {
                    "slug": slug,
                    "meta": item.get("meta") or "",
                    "title": item.get("title") or "",
                    "tags": item.get("tags") or [],
                }
            )
    if curated:
        return curated[:2]

    fallback: list[dict[str, Any]] = []
    for project in projects:
        if svc.get("slug") not in (project.get("serviceSlugs") or []):
            continue
        lead = project.get("lead") or ""
        title_extra = lead.split("،")[0] if lead else ""
        title = project.get("name") or ""
        if title_extra:
            title = f"{title} — {title_extra}"
        fallback.append(
            {
                "slug": project["slug"],
                "meta": " • ".join(
                    x for x in [project.get("year"), project.get("industry")] if x
                ),
                "title": title,
                "tags": (project.get("tags") or [])[:3],
            }
        )
        if len(fallback) >= 2:
            break
    return fallback


def _json_ld(svc: dict[str, Any], canonical: str, page_desc: str) -> str:
    name = svc.get("name") or ""
    graph: list[dict[str, Any]] = [
        {
            "@type": "Service",
            "name": name,
            "description": page_desc,
            "url": canonical,
            "provider": {
                "@type": "Organization",
                "name": "استودیو هش",
                "url": f"{BASE}/",
            },
            "areaServed": "IR",
            "inLanguage": "fa-IR",
        },
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "خانه", "item": f"{BASE}/"},
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "خدمات",
                    "item": f"{BASE}/services.html",
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": name,
                    "item": canonical,
                },
            ],
        },
    ]
    faqs = svc.get("faqs") or []
    if faqs:
        graph.append(
            {
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": item.get("q") or "",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": item.get("a") or "",
                        },
                    }
                    for item in faqs
                    if item.get("q") and item.get("a")
                ],
            }
        )
    return json.dumps(
        {"@context": "https://schema.org", "@graph": graph},
        ensure_ascii=False,
        separators=(",", ":"),
    )


def _hero_media(svc: dict[str, Any]) -> tuple[str, str]:
    """Return (media_class_suffix, inner_html)."""
    name = svc.get("name") or ""
    hero_image = svc.get("heroImage") or ""
    hero_kind = svc.get("heroKind") or ""
    media_mod = " sd-hero__media--contain" if hero_kind == "illustration" else ""
    if hero_kind == "preview" and svc.get("heroPixel"):
        inner = (
            '<div class="site-preview">'
            f'<div class="site-preview__pixel" aria-hidden="true">'
            f'<img src="{_attr(svc["heroPixel"])}" alt="" width="1280" height="720"></div>'
            f'<img class="site-preview__shot" src="{_attr(hero_image)}" alt="{_attr(name)}" '
            f'width="1280" height="720" loading="eager" fetchpriority="high" decoding="async">'
            "</div>"
        )
        return media_mod, inner
    inner = (
        f'<img data-field="hero-img" src="{_attr(hero_image)}" alt="{_attr(name)}" '
        f'width="540" height="380" loading="eager" fetchpriority="high" decoding="async">'
    )
    return media_mod, inner


def render_service(
    svc: dict[str, Any],
    projects: list[dict[str, Any]],
    articles: dict[str, dict[str, Any]],
    graph_services: dict[str, Any],
) -> str:
    slug = svc["slug"]
    name = svc.get("name") or ""
    seo = svc.get("seo") or {}
    page_title = (seo.get("title") or "").strip() or f"{name} | خدمات | استودیو هش"
    page_desc = (seo.get("description") or "").strip() or (svc.get("lead") or "")
    canonical = service_url(slug)
    hero_image = svc.get("heroImage") or "assets/images/home/logo.png"
    og_image = abs_url(hero_image)
    ld = _json_ld(svc, canonical, page_desc)
    theme = svc.get("theme") or "product"
    body_class = _body_classes(svc)
    media_mod, hero_inner = _hero_media(svc)

    stats_html = "".join(
        f'<li><div class="sd-stats__value">{escape_html(item.get("value") or "")}</div>'
        f'<div class="sd-stats__label">{escape_html(item.get("label") or "")}</div></li>'
        for item in (svc.get("stats") or [])
    )
    pains_html = "".join(
        f'<li class="sd-pain"><span class="sd-pain__icon">'
        f'{PAIN_NUMS[i] if i < len(PAIN_NUMS) else escape_html(str(i + 1))}</span>'
        f'<h3 class="sd-pain__title">{escape_html(item.get("title") or "")}</h3>'
        f'<p class="sd-pain__body">{escape_html(item.get("body") or "")}</p></li>'
        for i, item in enumerate(svc.get("pains") or [])
    )
    deliverables_html = "".join(
        f"<li>{escape_html(item)}</li>" for item in (svc.get("deliverables") or [])
    )
    capabilities_html = "".join(
        f'<li><span class="sd-caps__badge">{escape_html(item.get("badge") or "")}</span>'
        f'<span>{escape_html(item.get("text") or "")}</span></li>'
        for item in (svc.get("capabilities") or [])
    )
    steps_html = "".join(
        f'<li class="sd-step"><div class="sd-step__num">{escape_html(item.get("num") or "")}</div>'
        f'<h3 class="sd-step__title">{escape_html(item.get("title") or "")}</h3>'
        f'<p class="sd-step__desc">{escape_html(item.get("desc") or "")}</p></li>'
        for item in (svc.get("steps") or [])
    )
    tools_html = "".join(
        f'<li class="sd-tool"><div class="sd-tool__name">{escape_html(item.get("name") or "")}</div>'
        f'<p class="sd-tool__hint">{escape_html(item.get("hint") or "")}</p></li>'
        for item in (svc.get("tools") or [])
    )

    cases = resolve_cases(svc, projects)
    cases_html = "".join(
        (
            f'<a class="sd-case" href="/project/{_attr(item["slug"])}/" '
            f'data-cta="view-project" data-cta-location="service-cases" '
            f'data-project-slug="{_attr(item["slug"])}" data-service-slug="{_attr(slug)}">'
            f'<div class="sd-case__media"><div class="site-preview">'
            f'<div class="site-preview__pixel" aria-hidden="true">'
            f'<img src="assets/images/home/projects/{_attr(item["slug"])}-pixel.webp" '
            f'alt="{_attr(item.get("title") or "")}" width="1280" height="720" loading="lazy"></div>'
            f'<img class="site-preview__shot" src="assets/images/home/projects/{_attr(item["slug"])}-shot.webp" '
            f'alt="" width="1280" height="720" loading="lazy" aria-hidden="true">'
            f'</div></div><div class="sd-case__body">'
            f'<div class="sd-case__meta">{escape_html(item.get("meta") or "")}</div>'
            f'<h3 class="sd-case__title">{escape_html(item.get("title") or "")}</h3>'
            f'<div class="sd-case__tags">'
            + "".join(
                f'<span class="sd-case__tag">{escape_html(t)}</span>'
                for t in (item.get("tags") or [])
            )
            + f'</div><span class="sd-case__cta">مطالعه تجربه {escape_html((item.get("title") or "").split("—")[0].strip() or item.get("slug") or "")}</span>'
            + "</div></a>"
        )
        for item in cases
    )

    article_slugs = (graph_services.get(slug) or {}).get("articles") or []
    article_cards: list[str] = []
    for aslug in article_slugs[:3]:
        a = articles.get(aslug)
        if not a:
            continue
        article_cards.append(
            f'<a class="sd-article" href="/article/{_attr(a["slug"])}/" '
            f'data-cta="content-bridge" data-cta-location="service-bridge" '
            f'data-from-type="service" data-from-slug="{_attr(slug)}" '
            f'data-to-type="article" data-to-slug="{_attr(a["slug"])}" '
            f'data-content-slug="{_attr(a["slug"])}" data-service-slug="{_attr(slug)}">'
            f'<span class="sd-article__tag">{escape_html(a.get("tag") or "")}</span>'
            f'<h3 class="sd-article__title">{escape_html(a.get("title") or "")}</h3>'
            f'<p class="sd-article__lead">{escape_html((a.get("lead") or "")[:120])}</p>'
            f'<span class="sd-article__cta">مطالعه {escape_html(a.get("title") or "مقاله")}</span></a>'
        )
    show_articles = len(article_cards) > 0

    faqs_html = "".join(
        f'<details class="faq-item"{" open" if i == 0 else ""}>'
        f'<summary class="faq-item__question"><span class="faq-item__label">'
        f'{escape_html(item.get("q") or "")}</span>'
        f'<span class="faq-item__icon" aria-hidden="true"></span></summary>'
        f'<p class="faq-item__answer">{escape_html(item.get("a") or "")}</p></details>'
        for i, item in enumerate(svc.get("faqs") or [])
    )

    fit_items = svc.get("fitFor") or []
    fit_html = "".join(
        f'<li class="sd-fit__item">{escape_html(item)}</li>' for item in fit_items
    )
    show_fit = len(fit_items) > 0

    offers_html = ""
    from render_high_intent import load_high_intent_pages

    related_offers = []
    graph_solutions = (graph_services.get(slug) or {}).get("solutions") or []
    for offer in load_high_intent_pages():
        primary = offer.get("primaryService")
        related = list(offer.get("relatedServices") or [])
        oslug = offer.get("slug") or ""
        if slug == primary or slug in related or oslug in graph_solutions:
            related_offers.append((0 if slug == primary or oslug in graph_solutions else 1, offer))
    related_offers.sort(key=lambda item: (item[0], item[1].get("slug") or ""))
    shown = [o for _, o in related_offers[:2]]
    if shown:
        links = " · ".join(
            f'<a href="/solutions/{_attr(o["slug"])}/" '
            f'data-cta="content-bridge" data-cta-location="service-bridge" '
            f'data-from-type="service" data-from-slug="{_attr(slug)}" '
            f'data-to-type="solution" data-to-slug="{_attr(o["slug"])}" '
            f'data-service-slug="{_attr(slug)}">'
            f'بررسی مسیر {escape_html(o.get("name") or o["slug"])}</a>'
            for o in shown
        )
        offers_html = (
            '<p class="sd-fit-note__alt hi-service-offers">مسیر پیشنهاد مرتبط: '
            + links
            + "</p>"
        )

    return f"""<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{escape_html(page_desc)}">
  <meta name="robots" content="index,follow">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="fa_IR">
  <meta property="og:site_name" content="استودیو هش">
  <meta property="og:title" content="{escape_html(page_title)}">
  <meta property="og:description" content="{escape_html(page_desc)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{og_image}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape_html(page_title)}">
  <meta name="twitter:description" content="{escape_html(page_desc)}">
  <meta name="twitter:image" content="{og_image}">
  <title>{escape_html(page_title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;700;800&display=swap" id="hash-font-vazirmatn">
  <link rel="icon" href="assets/images/home/logo.png" type="image/png">
  <link rel="stylesheet" href="css/tokens.css">
  <link rel="stylesheet" href="css/reset.css">
  <link rel="stylesheet" href="css/base.css">
  <link rel="stylesheet" href="css/home.css">
  <link rel="stylesheet" href="css/services.css">
  <link rel="stylesheet" href="css/service-detail.css">
  <script type="application/ld+json" id="service-jsonld">{ld}</script>
</head>
<body class="{body_class}" data-slug="{_attr(slug)}" data-theme="{_attr(theme)}">
{GENERATED_BANNER}

  <div class="top-bar">
    <div class="container top-bar__inner">
      <p class="top-bar__text">برای شروع پروژه جدید آماده‌ایم — درباره ایده‌تان با ما صحبت کنید</p>
      <a href="contact.html" class="top-bar__btn">شروع پروژه</a>
    </div>
  </div>

  <header class="home-header" id="site-header">
    <div class="container home-header__inner">
      <a href="index.html" class="home-header__logo">
        <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
        <span class="home-header__logo-text">استودیو هش</span>
      </a>
      <nav class="home-header__nav" id="main-nav" aria-label="منوی اصلی">
        <a href="index.html" class="home-header__link">خانه</a>
        <a href="services.html" class="home-header__link is-active">خدمات</a>
        <a href="projects.html" class="home-header__link">پروژه‌ها</a>
        <a href="about.html" class="home-header__link">درباره ما</a>
        <a href="blog.html" class="home-header__link">بلاگ</a>
        <a href="contact.html" class="home-header__link">تماس با ما</a>
      </nav>
      <div class="home-header__actions">
        <a href="contact.html" class="btn btn--primary btn--header">شروع پروژه</a>
        <a href="contact.html" class="home-header__profile" aria-label="تماس با ما">
          <img src="assets/icons/profile.svg" alt="" width="39" height="39">
        </a>
        <button class="home-header__toggle" aria-label="باز کردن منو" aria-expanded="false" aria-controls="main-nav">
          <span></span><span></span><span></span>
        </button>
      </div>
    </div>
  </header>

  <main id="service-root">
    <section class="sd-hero">
      <div class="container sd-hero__grid">
        <div class="sd-hero__copy">
          <nav class="sd-breadcrumb" aria-label="مسیر">
            <a href="index.html">خانه</a>
            <span class="sd-breadcrumb__sep" aria-hidden="true">‹</span>
            <a href="services.html">خدمات</a>
            <span class="sd-breadcrumb__sep" aria-hidden="true">‹</span>
            <span class="sd-breadcrumb__current">{escape_html(name)}</span>
          </nav>
          <span class="badge badge--section">سرویس تخصصی استودیو هش</span>
          <h1 class="sd-hero__title">
            <span>{escape_html(svc.get("titleLead") or "")}</span>
            <span class="sd-hero__accent">{escape_html(svc.get("titleAccent") or "")}</span>
          </h1>
          <p class="sd-hero__lead">{escape_html(page_desc)}</p>
          <div class="sd-hero__actions">
            <a href="contact.html" class="btn btn--primary btn--lg" data-cta="start-project" data-cta-location="service-hero" data-service-slug="{_attr(slug)}">{escape_html(svc.get("ctaPrimary") or "شروع پروژه")}</a>
            <a href="/service/{_attr(slug)}/#cases" class="btn btn--outline btn--lg">نمونه‌کارهای مرتبط</a>
          </div>
        </div>
        <figure class="sd-hero__media{media_mod}" data-hero-media>
          {hero_inner}
        </figure>
      </div>
    </section>

    <section class="sd-section">
      <div class="container">
        <article class="sd-overview">
          <div class="sd-overview__copy">
            <h2 class="sd-overview__title">{escape_html(svc.get("overviewTitle") or "")}</h2>
            <p class="sd-overview__body">{escape_html(svc.get("overviewBody") or "")}</p>
          </div>
          <ul class="sd-stats" data-list="stats">{stats_html}</ul>
        </article>
      </div>
    </section>

    <section class="sd-section sd-section--cream" data-block="fit"{_hidden(show_fit)}>
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">مناسب کیست؟</span>
          <h2 class="section-head__title">{escape_html(svc.get("fitTitle") or "این خدمت برای چه تیم‌هایی است؟")}</h2>
        </div>
        <ul class="sd-fit" data-list="fitFor">{fit_html}</ul>
      </div>
    </section>

    <section class="sd-section sd-section--white">
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">{escape_html(svc.get("painBadge") or "")}</span>
          <h2 class="section-head__title">{escape_html(svc.get("painTitle") or "")}</h2>
        </div>
        <ul class="sd-pains" data-list="pains">{pains_html}</ul>
      </div>
    </section>

    <section class="sd-section">
      <div class="container sd-split">
        <div class="sd-panel">
          <h2 class="sd-panel__title">{escape_html(svc.get("deliverablesTitle") or "")}</h2>
          <p class="sd-panel__sub">{escape_html(svc.get("deliverablesSub") or "")}</p>
          <ul class="sd-checks" data-list="deliverables">{deliverables_html}</ul>
        </div>
        <div class="sd-panel">
          <h2 class="sd-panel__title">{escape_html(svc.get("capabilitiesTitle") or "")}</h2>
          <p class="sd-panel__sub">{escape_html(svc.get("capabilitiesSub") or "")}</p>
          <ul class="sd-caps" data-list="capabilities">{capabilities_html}</ul>
        </div>
      </div>
    </section>

    <section class="sd-section sd-section--white">
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">{escape_html(svc.get("processBadge") or "")}</span>
          <h2 class="section-head__title">{escape_html(svc.get("processTitle") or "")}</h2>
        </div>
        <ol class="sd-steps" data-list="steps">{steps_html}</ol>
      </div>
    </section>

    <section class="sd-section">
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">{escape_html(svc.get("toolsBadge") or "")}</span>
          <h2 class="section-head__title">{escape_html(svc.get("toolsTitle") or "")}</h2>
        </div>
        <ul class="sd-tools" data-list="tools">{tools_html}</ul>
      </div>
    </section>

    <section class="sd-section sd-section--white" id="cases">
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">{escape_html(svc.get("casesBadge") or "")}</span>
          <h2 class="section-head__title">{escape_html(svc.get("casesTitle") or "")}</h2>
        </div>
        <div class="sd-cases" data-list="cases">{cases_html}</div>
      </div>
    </section>

    <section class="sd-section sd-section--cream" data-block="service-articles"{_hidden(show_articles)}>
      <div class="container">
        <div class="section-head">
          <span class="badge badge--section">اتاق فکر</span>
          <h2 class="section-head__title">مقالات مرتبط با این خدمت</h2>
        </div>
        <div class="sd-articles" data-list="service-articles">{"".join(article_cards)}</div>
      </div>
    </section>

    <section class="sd-section">
      <div class="container">
        <div class="section-head section-head--start">
          <span class="badge badge--section">پاسخ به دغدغه‌های شما</span>
          <h2 class="section-head__title">{escape_html(svc.get("faqTitle") or "")}</h2>
        </div>
        <div class="faq-list sd-faq" data-list="faqs">{faqs_html}</div>
      </div>
    </section>

    <section class="home-final-cta">
      <div class="container">
        <article class="home-final-cta__card">
          <h2 class="home-final-cta__title">{escape_html(svc.get("ctaTitle") or "")}</h2>
          <p class="home-final-cta__desc">{escape_html(svc.get("ctaBody") or "")}</p>
          <div class="sd-fit-note" data-block="fit-note"{_hidden(show_fit)}>
            <p class="sd-fit-note__title">این خدمت برای شما مناسب است اگر…</p>
            <ul class="sd-fit-note__list">{fit_html}</ul>
            <p class="sd-fit-note__alt">اگر هنوز مطمئن نیستید کدام مسیر مناسب شماست، از <a href="/#service-fit" data-cta="service-fit-guide" data-cta-location="service-cta">راهنمای انتخاب خدمت</a> استفاده کنید.</p>
            {offers_html}
          </div>
          <div class="home-final-cta__actions">
            <a href="contact.html" class="btn btn--primary btn--lg" data-cta="start-project" data-cta-location="service-cta" data-service-slug="{_attr(slug)}">درباره پروژه شما صحبت کنیم</a>
            <a href="/#service-fit" class="btn btn--outline btn--lg" data-cta="service-fit-guide" data-cta-location="service-cta">راهنمای انتخاب خدمت</a>
          </div>
        </article>
      </div>
    </section>
  </main>

  <footer class="home-footer">
    <div class="container">
      <div class="home-footer__grid">
        <div class="home-footer__brand">
          <img src="assets/images/home/logo.png" alt="لوگوی استودیو هش" width="36" height="36">
          <div class="home-footer__brand-name">استودیو هش</div>
          <p class="home-footer__brand-desc">طراحی و توسعه محصولات دیجیتال برای استارتاپ‌ها و شرکت‌های پیشرو — از ایده تا تجربه‌ای که کاربران عاشقش می‌شوند.</p>
          <div class="home-footer__location">
            <span class="home-footer__location-icon" aria-hidden="true">📍</span>
            <span data-studio="address-short">تهران، یوسف‌آباد، جهان‌آرا، کوچه ۴۳</span>
          </div>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">دسترسی سریع</h3>
          <nav class="home-footer__links" aria-label="لینک‌های فوتر">
            <a href="index.html" class="home-footer__link">خانه اصلی</a>
            <a href="services.html" class="home-footer__link">خدمات</a>
            <a href="projects.html" class="home-footer__link">پروژه‌ها و نمونه‌کارها</a>
            <a href="about.html" class="home-footer__link">درباره ما</a>
            <a href="blog.html" class="home-footer__link">وبلاگ تخصصی</a>
            <a href="contact.html" class="home-footer__link">تماس با ما</a>
          </nav>
        </div>
        <div class="home-footer__links-col">
          <h3 class="home-footer__heading">خدمات ما</h3>
          <nav class="home-footer__links">
            <a href="/service/product/" class="home-footer__link">طراحی محصول</a>
            <a href="/service/ui-ux/" class="home-footer__link">طراحی UI/UX</a>
            <a href="/service/web/" class="home-footer__link">توسعه وب مدرن</a>
            <a href="/service/mobile/" class="home-footer__link">توسعه اپلیکیشن موبایل</a>
            <a href="/service/mvp/" class="home-footer__link">راه‌اندازی MVP</a>
            <a href="/service/ai/" class="home-footer__link">یکپارچه‌سازی هوش مصنوعی</a>
            <a href="/service/seo/" class="home-footer__link">سئو و رشد</a>
            <a href="/service/consulting/" class="home-footer__link">مشاوره محصول</a>
          </nav>
        </div>
        <div class="home-footer__newsletter-col">
          <h3 class="home-footer__heading">پروژه بعدی شما</h3>
          <p class="home-footer__newsletter-desc">ایده، محصول نیمه‌کاره یا بازطراحی — مسیر را با هم مشخص می‌کنیم.</p>
          <a class="btn btn--primary" href="/contact.html" data-cta="start-project" data-cta-location="footer">شروع پروژه</a>
          <div class="home-footer__social" data-studio="social" data-studio-social-class="home-footer__social-link">
            <a href="https://www.instagram.com/hashstudio.ir/" class="home-footer__social-link" aria-label="اینستاگرام" target="_blank" rel="noopener noreferrer">IG</a>
          </div>
        </div>
      </div>
      <div class="home-footer__bottom">
        <span>تمامی حقوق مادی و معنوی محفوظ است © ۱۴۰۵ استودیو هش</span>
        <span>طراحی و توسعه با ■ در استودیو هش</span>
      </div>
    </div>
  </footer>

  <script src="js/main.js"></script>
  <script src="/js/studio-info.js"></script>
  <script src="/js/analytics.js"></script>
  <script src="/js/studio-chrome.js"></script>
</body>
</html>
"""


def generate_services(data: dict[str, Any], root: Path) -> int:
    services = data.get("services") or []
    if not services:
        raise RuntimeError("site-data.json has zero services — refusing to generate")
    projects = data.get("projects") or []
    articles = data.get("articles") or {}
    graph_services = (data.get("graph") or {}).get("services") or {}
    written = 0
    for svc in services:
        slug = svc.get("slug")
        if not slug:
            continue
        html = render_service(svc, projects, articles, graph_services)
        out_dir = root / "service" / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(html, encoding="utf-8")
        written += 1
    if written == 0:
        raise RuntimeError("No service pages were written")
    return written
