#!/usr/bin/env python3
"""Lightweight site QA for Hash Studio static pages.

Checks:
  - missing title / meta description / canonical / H1
  - duplicate canonical URLs
  - article/project/service folder integrity
  - article SEO (canonical, OG, JSON-LD, lang/dir)
  - broken internal href targets (basic)
  - images missing width/height attributes (warn)
  - query canonicals

Usage:
  python3 scripts/validate-site.py
  npm run validate
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://hashstudio.ir"

TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
DESC_RE = re.compile(
    r'<meta\s+[^>]*name=["\']description["\'][^>]*content=["\'](.*?)["\']',
    re.I | re.S,
)
DESC_RE2 = re.compile(
    r'<meta\s+[^>]*content=["\'](.*?)["\'][^>]*name=["\']description["\']',
    re.I | re.S,
)
CANON_RE = re.compile(
    r'<link\s+[^>]*rel=["\']canonical["\'][^>]*href=["\'](.*?)["\']',
    re.I | re.S,
)
CANON_RE2 = re.compile(
    r'<link\s+[^>]*href=["\'](.*?)["\'][^>]*rel=["\']canonical["\']',
    re.I | re.S,
)
H1_RE = re.compile(r"<h1\b", re.I)
HREF_RE = re.compile(r'\bhref=["\']([^"\'#]+)["\']', re.I)
IMG_RE = re.compile(r"<img\b[^>]*>", re.I)
WIDTH_RE = re.compile(r"\bwidth=", re.I)
HEIGHT_RE = re.compile(r"\bheight=", re.I)
SLUG_RE = re.compile(r"^[a-z0-9-]+$")
CTA_RE = re.compile(r'\bdata-cta=["\']([^"\']+)["\']', re.I)
ALLOWED_CTAS = {
    "start-project",
    "view-projects",
    "view-project",
    "view-service",
    "view-article",
    "view-blog",
    "external-project",
    "contact-form",
    "contact-submit",
    "service-fit-select",
    "service-fit-recommendation",
    "service-fit-service",
    "service-fit-contact",
    "service-fit-guide",
    "high-intent-cta",
    "high-intent-project",
}
SENSITIVE_TRACK_RE = re.compile(
    r"""\.track\s*\(\s*['\"][^'\"]+['\"]\s*,\s*\{[^}]*(?:email|phone|message|filename)\s*:""",
    re.I,
)
OG_RE = re.compile(r'<meta\s+[^>]*property=["\']og:(title|description|image|url|type)["\']', re.I)
LD_RE = re.compile(r'<script[^>]*type=["\']application/ld\+json["\']', re.I)
LANG_RE = re.compile(r'<html[^>]*\blang=["\']fa["\']', re.I)
DIR_RE = re.compile(r'<html[^>]*\bdir=["\']rtl["\']', re.I)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def meta_desc(html: str) -> str | None:
    m = DESC_RE.search(html) or DESC_RE2.search(html)
    return m.group(1).strip() if m else None


def canonical(html: str) -> str | None:
    m = CANON_RE.search(html) or CANON_RE2.search(html)
    return m.group(1).strip() if m else None


def title(html: str) -> str | None:
    m = TITLE_RE.search(html)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else None


def resolve_href(page: Path, href: str, has_base_root: bool) -> Path | None:
    if href.startswith(("http://", "https://", "mailto:", "tel:", "data:", "javascript:")):
        return None
    href = href.split("?")[0].split("#")[0]
    if not href:
        return None
    if href.startswith("/"):
        target = ROOT / href.lstrip("/")
    elif has_base_root or not href.startswith("."):
        target = ROOT / href
    else:
        target = (page.parent / href).resolve()
        try:
            target.relative_to(ROOT)
        except ValueError:
            return None
    if target.is_dir():
        index = target / "index.html"
        return index if index.exists() else target
    return target


def validate_detail_page(
    rel: str,
    slug: str,
    html: str,
    kind: str,
    errors: list[str],
    warnings: list[str] | None = None,
) -> None:
    warn = warnings if warnings is not None else errors
    expected = f"{BASE}/{kind}/{slug}/"
    c = canonical(html)
    if c != expected:
        errors.append(f"{rel}: canonical expected {expected} got {c}")
    if not LANG_RE.search(html):
        errors.append(f'{rel}: missing lang="fa"')
    if not DIR_RE.search(html):
        errors.append(f'{rel}: missing dir="rtl"')
    if not meta_desc(html):
        errors.append(f"{rel}: missing meta description")
    og_props = {m.group(1).lower() for m in OG_RE.finditer(html)}
    for prop in ("title", "description", "image", "url", "type"):
        if prop not in og_props:
            errors.append(f"{rel}: missing og:{prop}")
    if not LD_RE.search(html):
        errors.append(f"{rel}: missing JSON-LD")
    h1_count = len(H1_RE.findall(html))
    if h1_count != 1:
        errors.append(f"{rel}: expected exactly 1 H1, found {h1_count}")
    for legacy in (
        "article.html?slug=",
        "project.html?slug=",
        "service.html?slug=",
    ):
        if legacy in html:
            errors.append(f"{rel}: contains legacy {legacy} link")
    banner_by_kind = {
        "article": "Generated by scripts/build-content.py",
        "project": "Generated by scripts/build-projects.py",
        "service": "Generated by scripts/build-services.py",
        "solutions": "Generated by scripts/build-high-intent.py",
    }
    expected_banner = banner_by_kind.get(kind)
    if expected_banner and expected_banner not in html:
        errors.append(f"{rel}: missing {expected_banner} banner")
    # Primary root must be visible
    if kind == "project" and re.search(r'id="project-root"[^>]*\bhidden\b', html):
        errors.append(f"{rel}: #project-root is hidden")
    if kind == "service" and re.search(r'id="service-root"[^>]*\bhidden\b', html):
        errors.append(f"{rel}: #service-root is hidden")
    # Must not load full datasets on detail pages
    for banned in (
        "projects-data.js",
        "services-data.js",
        "articles-data.js",
        "content-graph.js",
        "high-intent-data.js",
    ):
        if re.search(
            rf'<script[^>]+src=["\'][^"\']*{re.escape(banned)}',
            html,
            re.I,
        ):
            errors.append(f"{rel}: must not load {banned}")
    # Breadcrumb present
    if kind == "project" and "pd-breadcrumb" not in html:
        errors.append(f"{rel}: missing project breadcrumb")
    if kind == "service" and "sd-breadcrumb" not in html:
        errors.append(f"{rel}: missing service breadcrumb")
    if kind == "solutions" and "sd-breadcrumb" not in html:
        errors.append(f"{rel}: missing solution breadcrumb")
    if kind == "project" and "CreativeWork" not in html:
        errors.append(f"{rel}: missing CreativeWork JSON-LD")
    if kind == "service" and '"@type":"Service"' not in html.replace(" ", ""):
        errors.append(f"{rel}: missing Service JSON-LD")
    if kind == "solutions" and '"@type":"Service"' not in html.replace(" ", ""):
        errors.append(f"{rel}: missing Service JSON-LD (about Service)")
    if kind in ("service", "solutions") and '"@type":"FAQPage"' not in html.replace(" ", "") and "faq-item" in html:
        msg = f"{rel}: has FAQ UI but missing FAQPage JSON-LD"
        if kind == "solutions":
            errors.append(msg)
        else:
            warn.append(msg)
    if "BreadcrumbList" not in html:
        errors.append(f"{rel}: missing BreadcrumbList JSON-LD")
    # Body text: require some Persian content beyond chrome
    if len(re.sub(r"\s+", "", html)) < 2000:
        errors.append(f"{rel}: generated HTML looks too thin")

    # Fail empty primary template shells (pre-SSG pattern)
    h1_m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.I | re.S)
    if h1_m and not re.sub(r"<[^>]+>", "", h1_m.group(1)).strip():
        errors.append(f"{rel}: empty H1 (content not statically rendered)")
    if kind == "solutions" and "hi-case__why" not in html:
        errors.append(f"{rel}: missing per-project relevance (hi-case__why)")
    if kind == "solutions" and 'href="/#service-fit"' not in html:
        errors.append(f"{rel}: missing Service Fit guide CTA")
    for field in ("title", "lead", "name"):
        for m in re.finditer(
            rf"<([a-z0-9]+)[^>]*data-field=\"{field}\"[^>]*>(.*?)</\1>",
            html,
            re.I | re.S,
        ):
            text = re.sub(r"<[^>]+>", "", m.group(2)).strip()
            if not text:
                errors.append(
                    f"{rel}: empty data-field=\"{field}\" (content not statically rendered)"
                )
    if kind == "project":
        if "pd-hero__title" not in html:
            errors.append(f"{rel}: missing project hero title markup")
        if not re.search(r'data-list="toc">\s*<li>', html):
            # TOC may be hidden when <3 sections; allow empty only if toc wrap hidden
            if not re.search(r'data-pd-toc[^>]*\bhidden\b', html) and 'data-pd-toc hidden' not in html:
                if 'pd-toc__link' not in html:
                    errors.append(f"{rel}: project TOC empty but not hidden")
        if "projects-data.js" in html and "<script" in html:
            pass  # already checked via script src
    if kind == "service":
        if "sd-hero__title" not in html and "sd-hero__lead" not in html:
            errors.append(f"{rel}: missing service hero content markup")


def validate_article_page(
    rel: str, slug: str, html: str, errors: list[str], warnings: list[str] | None = None
) -> None:
    validate_detail_page(rel, slug, html, "article", errors, warnings)
    if "BlogPosting" not in html and "Article" not in html:
        errors.append(f"{rel}: missing BlogPosting/Article JSON-LD")
    if "article-breadcrumb" not in html and "خانه" not in html:
        errors.append(f"{rel}: missing article breadcrumb")

def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []
    canon_map: dict[str, list[str]] = defaultdict(list)

    project_dirs = [p for p in (ROOT / "project").iterdir() if p.is_dir()]
    service_dirs = [p for p in (ROOT / "service").iterdir() if p.is_dir()]
    article_dirs = (
        [p for p in (ROOT / "article").iterdir() if p.is_dir()]
        if (ROOT / "article").exists()
        else []
    )

    for d in project_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid project slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing project index: project/{d.name}/index.html")

    for d in service_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid service slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing service index: service/{d.name}/index.html")

    for d in article_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid article slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing article index: article/{d.name}/index.html")

    # articles-data.js ↔ article/<slug>/ must match 1:1
    articles_js = (ROOT / "js/articles-data.js").read_text(encoding="utf-8")
    data_article_slugs = set(re.findall(r'^  "([a-z0-9-]+)": \{', articles_js, re.M))
    folder_article_slugs = {d.name for d in article_dirs}
    for slug in sorted(data_article_slugs - folder_article_slugs):
        errors.append(f"articles-data slug missing generated page: article/{slug}/")
    for slug in sorted(folder_article_slugs - data_article_slugs):
        errors.append(f"generated article folder not in articles-data.js: article/{slug}/")

    # projects-data ↔ project folders
    projects_js = (ROOT / "js/projects-data.js").read_text(encoding="utf-8")
    data_project_slugs = set(re.findall(r"^\s+slug:\s*'([a-z0-9-]+)',\s*$", projects_js, re.M))
    folder_project_slugs = {d.name for d in project_dirs}
    for slug in sorted(data_project_slugs - folder_project_slugs):
        errors.append(f"projects-data slug missing page: project/{slug}/")
    for slug in sorted(folder_project_slugs - data_project_slugs):
        errors.append(f"project folder not in projects-data.js: project/{slug}/")

    # services-data ↔ service folders
    services_js = (ROOT / "js/services-data.js").read_text(encoding="utf-8")
    data_service_slugs = set(re.findall(r"^\s+slug:\s*'([a-z0-9-]+)',\s*$", services_js, re.M))
    folder_service_slugs = {d.name for d in service_dirs}
    for slug in sorted(data_service_slugs - folder_service_slugs):
        errors.append(f"services-data slug missing page: service/{slug}/")
    for slug in sorted(folder_service_slugs - data_service_slugs):
        errors.append(f"service folder not in services-data.js: service/{slug}/")

    html_files = sorted(ROOT.rglob("*.html"))
    skip_parts = {"node_modules", ".git"}
    checked = 0

    for path in html_files:
        if any(part in skip_parts for part in path.parts):
            continue
        rel = str(path.relative_to(ROOT))
        html = read(path)
        has_base_root = bool(re.search(r'<base\s+[^>]*href=["\']/["\']', html, re.I))
        checked += 1

        t = title(html)
        if not t:
            errors.append(f"{rel}: missing <title>")

        # Compatibility / legacy shells intentionally thin
        if rel in {"project.html", "service.html", "article.html"}:
            continue

        if rel.startswith("article/") and rel.endswith("/index.html"):
            validate_article_page(rel, path.parent.name, html, errors, warnings)
        elif rel.startswith("project/") and rel.endswith("/index.html"):
            validate_detail_page(rel, path.parent.name, html, "project", errors, warnings)
        elif rel.startswith("service/") and rel.endswith("/index.html"):
            validate_detail_page(rel, path.parent.name, html, "service", errors, warnings)
        elif rel.startswith("solutions/") and rel.endswith("/index.html"):
            validate_detail_page(rel, path.parent.name, html, "solutions", errors, warnings)

        d = meta_desc(html)
        if not d and rel != "404.html":
            warnings.append(f"{rel}: missing meta description")

        c = canonical(html)
        if c:
            canon_map[c].append(rel)
            if "project.html?slug=" in c or "service.html?slug=" in c or "article.html?slug=" in c:
                errors.append(f"{rel}: query canonical {c}")
            if "localhost" in c or c.startswith("/"):
                errors.append(f"{rel}: bad canonical {c}")
            if rel.startswith("project/") and "/project/" not in c:
                errors.append(f"{rel}: canonical should be /project/{{slug}}/ → {c}")
            if rel.startswith("service/") and "/service/" not in c:
                errors.append(f"{rel}: canonical should be /service/{{slug}}/ → {c}")
            if rel.startswith("article/") and f"/article/{path.parent.name}/" not in c:
                errors.append(f"{rel}: canonical should be /article/{{slug}}/ → {c}")
        elif rel.endswith("index.html") or rel in {
            "index.html",
            "projects.html",
            "services.html",
            "about.html",
            "contact.html",
            "blog.html",
        }:
            if rel != "404.html":
                warnings.append(f"{rel}: missing canonical")

        if not H1_RE.search(html) and rel != "404.html":
            if 'data-field="name"' not in html and 'data-field="title"' not in html:
                warnings.append(f"{rel}: missing H1")

        for href in HREF_RE.findall(html):
            target = resolve_href(path, href, has_base_root)
            if target is None:
                continue
            if not target.exists():
                pretty = ROOT / href.lstrip("/").rstrip("/").split("?")[0]
                if pretty.is_dir() and (pretty / "index.html").exists():
                    continue
                errors.append(f"{rel}: broken link → {href}")

        for img in IMG_RE.findall(html):
            if "src=" not in img.lower():
                continue
            if not WIDTH_RE.search(img) or not HEIGHT_RE.search(img):
                warnings.append(f"{rel}: img missing width/height")

    for c, files in sorted(canon_map.items()):
        if len(files) > 1:
            errors.append(f"duplicate canonical {c}: {', '.join(files)}")

    # Conversion / analytics integrity
    analytics_js = ROOT / "js" / "analytics.js"
    contact_js = ROOT / "js" / "contact.js"
    if not analytics_js.is_file():
        errors.append("js/analytics.js missing")
    else:
        atext = analytics_js.read_text(encoding="utf-8")
        if "hashstudio_attribution" not in atext:
            errors.append("js/analytics.js: missing hashstudio_attribution key")
        if "HashAnalytics" not in atext:
            errors.append("js/analytics.js: missing HashAnalytics export")
        if atext.count("HashAnalytics.__booted") < 1:
            errors.append("js/analytics.js: missing boot guard")
        if SENSITIVE_TRACK_RE.search(atext):
            errors.append("js/analytics.js: possible sensitive field in track payload")
    if contact_js.is_file():
        ctext = contact_js.read_text(encoding="utf-8")
        for required in (
            "contact_form_start",
            "contact_form_validation_error",
            "contact_form_submit_intent",
            "contact_email_open",
            "اطلاعات مسیر ورود",
            "has_goal",
            "method: 'mailto'",
        ):
            if required not in ctext:
                errors.append(f"js/contact.js: missing {required}")
        if SENSITIVE_TRACK_RE.search(ctext):
            errors.append("js/contact.js: possible sensitive field in track payload")
        if re.search(r"track\([^)]*fieldValue\(['\"]email", ctext):
            errors.append("js/contact.js: must not track email value")
        if re.search(
            r"contact_form_submit_intent[\s\S]{0,240}\b(name|email|phone|message)\s*:",
            ctext,
        ):
            errors.append("js/contact.js: submit_intent must not include PII keys")

    # analytics hardening markers
    if analytics_js.is_file():
        atext = analytics_js.read_text(encoding="utf-8")
        for required in (
            "last_page_path",
            "ensureLeadContext",
            "sanitizeProps",
            "cleanDestination",
        ):
            if required not in atext:
                errors.append(f"js/analytics.js: missing {required}")
        if "external_project" in atext and "cta === 'external_project'" in atext:
            errors.append("js/analytics.js: drop underscore CTA aliases; use kebab-case only")

    # Key pages must load analytics abstraction
    for rel in (
        "index.html",
        "contact.html",
        "projects.html",
        "services.html",
        "blog.html",
        "about.html",
    ):
        html = (ROOT / rel).read_text(encoding="utf-8")
        script_hits = len(re.findall(r'<script[^>]+src=["\'][^"\']*analytics\.js', html, re.I))
        if script_hits != 1:
            errors.append(f"{rel}: expected 1 analytics.js script, found {script_hits}")
        for cta in CTA_RE.findall(html):
            if cta not in ALLOWED_CTAS:
                errors.append(f"{rel}: unknown data-cta={cta}")
            if "_" in cta:
                errors.append(f"{rel}: CTA must be kebab-case, got {cta}")

    contact_html = (ROOT / "contact.html").read_text(encoding="utf-8")
    if 'data-cta="contact-submit"' not in contact_html:
        errors.append("contact.html: submit button missing data-cta=contact-submit")
    if 'id="ct-fit-hint"' not in contact_html:
        warnings.append("contact.html: missing ct-fit-hint for service-fit context")

    # Service Fit homepage experience
    index_html = (ROOT / "index.html").read_text(encoding="utf-8")
    fit_js = ROOT / "js" / "service-fit.js"
    if 'data-service-fit' not in index_html or 'id="service-fit"' not in index_html:
        errors.append("index.html: missing Service Fit section (data-service-fit / #service-fit)")
    if 'id="fit"' not in index_html:
        warnings.append("index.html: missing Who we help section (#fit) before Service Fit")
    if "js/service-fit.js" not in index_html:
        errors.append("index.html: must load js/service-fit.js")
    # Script order: projects-data + analytics before service-fit
    if "js/service-fit.js" in index_html:
        sf_pos = index_html.find("js/service-fit.js")
        if index_html.find("js/projects-data.js") > sf_pos or index_html.find("js/projects-data.js") < 0:
            errors.append("index.html: projects-data.js must load before service-fit.js")
        if index_html.find("js/analytics.js") > sf_pos or index_html.find("js/analytics.js") < 0:
            errors.append("index.html: analytics.js must load before service-fit.js")
    if not fit_js.is_file():
        errors.append("js/service-fit.js missing")
    else:
        fit_text = fit_js.read_text(encoding="utf-8")
        for event in (
            "service_fit_started",
            "service_fit_recommendation_viewed",
        ):
            if event not in fit_text:
                errors.append(f"js/service-fit.js: missing event {event}")
        analytics_text = (
            analytics_js.read_text(encoding="utf-8") if analytics_js.is_file() else ""
        )
        if "service_fit_selected" not in analytics_text:
            errors.append("js/analytics.js: missing service_fit_selected")
        if "service_fit_cta_click" not in analytics_text:
            errors.append("js/analytics.js: missing service_fit_cta_click")
        if "service_fit_selector_click" in analytics_text or "service-fit-selector" in analytics_text:
            warnings.append("js/analytics.js: unused service-fit-selector taxonomy still present")

        # Extract FIT_MAP keys (quoted or bare) that own a service: field
        map_keys = {
            a or b
            for a, b in re.findall(
                r"(?:['\"]([a-z0-9-]+)['\"]|([a-z]+))\s*:\s*\{\s*\n\s*service:",
                fit_text,
            )
        }
        html_intents = set(re.findall(r'data-fit-intent=["\']([a-z0-9-]+)["\']', index_html))
        for intent in sorted(html_intents - map_keys):
            errors.append(
                f"Service Fit mismatch: index.html intent '{intent}' missing from FIT_MAP"
            )
        for intent in sorted(map_keys - html_intents):
            errors.append(
                f"Service Fit mismatch: FIT_MAP intent '{intent}' missing homepage button"
            )

        canonical_intents = ("idea", "existing", "website", "technical", "unknown")
        obsolete_intents = ("new-product", "existing-product")
        for intent in canonical_intents:
            count = len(
                re.findall(
                    rf'data-fit-intent=["\']{re.escape(intent)}["\']',
                    index_html,
                )
            )
            if count != 1:
                errors.append(
                    f"index.html: canonical fit intent '{intent}' must appear exactly once, found {count}"
                )
            if intent not in map_keys:
                errors.append(f"js/service-fit.js: FIT_MAP missing canonical intent '{intent}'")
        for intent in obsolete_intents:
            if intent in map_keys or re.search(
                rf"['\"]?{re.escape(intent)}['\"]?\s*:\s*\{{",
                fit_text,
            ):
                errors.append(
                    f"js/service-fit.js: obsolete FIT_MAP intent '{intent}' must be removed"
                )
            if f'data-fit-intent="{intent}"' in index_html or f"data-fit-intent='{intent}'" in index_html:
                errors.append(f"index.html: obsolete fit intent '{intent}' must be removed")

        for svc in re.findall(r"service:\s*'([a-z0-9-]+)'", fit_text):
            if svc not in folder_service_slugs:
                errors.append(f"js/service-fit.js: unknown service slug {svc}")
        for sec in re.findall(r"secondary:\s*'([a-z0-9-]+)'", fit_text):
            if sec not in folder_service_slugs:
                errors.append(f"js/service-fit.js: unknown secondary service {sec}")
        for proj in re.findall(r"project:\s*'([a-z0-9-]+)'", fit_text):
            if proj not in folder_project_slugs:
                errors.append(f"js/service-fit.js: unknown project slug {proj}")

        if "project_slug: map.project" not in fit_text:
            errors.append(
                "js/service-fit.js: rememberFit must persist project_slug from FIT_MAP"
            )

    # High-intent proposal pages (Phase 14)
    hi_data = ROOT / "js" / "high-intent-data.js"
    hi_root = ROOT / "solutions"
    if hi_data.is_file():
        try:
            sys.path.insert(0, str(ROOT / "scripts"))
            from render_high_intent import load_high_intent_pages

            hi_pages = load_high_intent_pages()
        except Exception as exc:  # noqa: BLE001
            errors.append(f"high-intent-data.js: failed to load ({exc})")
            hi_pages = []

        hi_slugs = [p.get("slug") for p in hi_pages if p.get("slug")]
        if len(hi_slugs) != len(set(hi_slugs)):
            errors.append("high-intent: duplicate slugs in HASH_HIGH_INTENT_PAGES")
        if len(hi_slugs) < 3:
            errors.append("high-intent: expected at least 3 proposal pages")

        if (ROOT / "for").is_dir():
            errors.append("high-intent: legacy for/ directory must be removed (use solutions/)")

        vercel_txt = (ROOT / "vercel.json").read_text(encoding="utf-8") if (ROOT / "vercel.json").is_file() else ""
        redirects_txt = (ROOT / "_redirects").read_text(encoding="utf-8") if (ROOT / "_redirects").is_file() else ""
        htaccess_txt = (ROOT / ".htaccess").read_text(encoding="utf-8") if (ROOT / ".htaccess").is_file() else ""
        if "/for/:slug" not in vercel_txt or "/solutions/:slug/" not in vercel_txt:
            errors.append("high-intent: vercel.json missing /for/:slug → /solutions/:slug/ redirect")
        if "/for/:slug" not in redirects_txt or "/solutions/:slug/" not in redirects_txt:
            errors.append("high-intent: _redirects missing /for/:slug → /solutions/:slug/ redirect")
        if "for/" not in htaccess_txt or "solutions/" not in htaccess_txt:
            errors.append("high-intent: .htaccess missing /for/ → /solutions/ RewriteRule")

        folder_hi = {
            d.name
            for d in hi_root.iterdir()
            if hi_root.is_dir() and d.is_dir() and (d / "index.html").is_file()
        } if hi_root.is_dir() else set()

        for slug in hi_slugs:
            if not SLUG_RE.match(slug or ""):
                errors.append(f"high-intent: invalid slug {slug}")
            if slug not in folder_hi:
                errors.append(f"high-intent: missing generated page solutions/{slug}/")

        for slug in sorted(folder_hi - set(hi_slugs)):
            errors.append(f"high-intent: orphan solutions/{slug}/ not in high-intent-data.js")

        hi_titles: set[str] = set()
        hi_descs: set[str] = set()
        for page in hi_pages:
            slug = page.get("slug") or ""
            seo = page.get("seo") or {}
            page_title = (seo.get("title") or "").strip()
            page_desc = (seo.get("description") or "").strip()
            if not page_title:
                errors.append(f"high-intent/{slug}: missing seo.title")
            elif page_title in hi_titles:
                errors.append(f"high-intent/{slug}: duplicate seo.title")
            else:
                hi_titles.add(page_title)
            if not page_desc:
                errors.append(f"high-intent/{slug}: missing seo.description")
            elif page_desc in hi_descs:
                errors.append(f"high-intent/{slug}: duplicate seo.description")
            else:
                hi_descs.add(page_desc)

            primary = page.get("primaryService") or ""
            if primary not in folder_service_slugs:
                errors.append(f"high-intent/{slug}: unknown primaryService {primary}")
            if slug in folder_service_slugs:
                errors.append(
                    f"high-intent/{slug}: cannibalization — slug collides with /service/{slug}/"
                )
            # Reject thin service-clone slugs (audit gate)
            if slug in {
                "product-design",
                "ui-ux-design",
                "mvp-development",
                "web-design-development",
                "technical-seo",
                "product",
                "ui-ux",
                "web",
                "mvp",
                "seo",
            }:
                errors.append(
                    f"high-intent/{slug}: rejected service-clone slug — improve /service/ instead"
                )
            for svc in page.get("relatedServices") or []:
                if svc not in folder_service_slugs:
                    errors.append(f"high-intent/{slug}: unknown relatedService {svc}")
            for proj in page.get("projects") or []:
                if isinstance(proj, dict):
                    proj_slug = proj.get("slug") or ""
                    why = (proj.get("why") or "").strip()
                else:
                    proj_slug = str(proj or "")
                    why = ""
                if proj_slug not in folder_project_slugs:
                    errors.append(f"high-intent/{slug}: unknown project {proj_slug}")
                elif len(why) < 40:
                    errors.append(
                        f"high-intent/{slug}: project {proj_slug} needs why relevance (≥40 chars)"
                    )
            for art in page.get("articles") or []:
                if art not in data_article_slugs:
                    errors.append(f"high-intent/{slug}: unknown article {art}")

            cta_primary = ((page.get("cta") or {}).get("primary") or "").strip()
            if not cta_primary or cta_primary in {"تماس با ما", "شروع یک پروژه", "شروع پروژه"}:
                errors.append(
                    f"high-intent/{slug}: cta.primary must be contextual (not generic)"
                )

            fit_not = page.get("fitNotFor") or {}
            if len(fit_not.get("items") or []) < 2:
                errors.append(f"high-intent/{slug}: fitNotFor needs at least 2 items")

            html_path = hi_root / slug / "index.html"
            if html_path.is_file():
                html = html_path.read_text(encoding="utf-8")
                canon = canonical(html)
                expected_canon = f"{BASE}/solutions/{slug}/"
                if canon != expected_canon:
                    errors.append(
                        f"solutions/{slug}/: canonical expected {expected_canon}, got {canon}"
                    )
                if 'id="high-intent-jsonld"' not in html and "application/ld+json" not in html:
                    errors.append(f"solutions/{slug}/: missing JSON-LD")
                if f'href="contact.html?service={primary}&intent={slug}"' not in html:
                    errors.append(f"solutions/{slug}/: missing contextual contact CTA")
                if 'href="/#service-fit"' not in html:
                    errors.append(f"solutions/{slug}/: missing Service Fit guide CTA")
                sm_path = ROOT / "sitemap.xml"
                if sm_path.is_file():
                    sm = sm_path.read_text(encoding="utf-8")
                    if expected_canon not in sm:
                        errors.append(f"solutions/{slug}/: missing from sitemap.xml")

        analytics_text = (
            analytics_js.read_text(encoding="utf-8") if analytics_js.is_file() else ""
        )
        for event in (
            "high_intent_page_view",
            "high_intent_cta_click",
            "high_intent_project_click",
        ):
            if event not in analytics_text:
                errors.append(f"js/analytics.js: missing {event}")

        contact_text = (ROOT / "js" / "contact.js").read_text(encoding="utf-8")
        for slug in hi_slugs:
            if f"'{slug}'" not in contact_text and f'"{slug}"' not in contact_text:
                errors.append(
                    f"js/contact.js: KNOWN_INTENTS missing high-intent slug '{slug}'"
                )
            if f"'{slug}'" not in analytics_text and f'"{slug}"' not in analytics_text:
                errors.append(
                    f"js/analytics.js: SOLUTIONS_PRIMARY missing high-intent slug '{slug}'"
                )
            page = next(p for p in hi_pages if p.get("slug") == slug)
            primary = page.get("primaryService") or ""
            if primary:
                norm = analytics_text.replace('"', "'")
                if f"'{slug}': '{primary}'" not in norm:
                    errors.append(
                        f"js/analytics.js: SOLUTIONS_PRIMARY['{slug}'] should be '{primary}'"
                    )

    # Generated detail pages: analytics + CTA hygiene
    solutions_dirs = (
        sorted([d for d in (ROOT / "solutions").iterdir() if d.is_dir()])
        if (ROOT / "solutions").is_dir()
        else []
    )
    for kind, dirs in (
        ("project", project_dirs),
        ("service", service_dirs),
        ("article", article_dirs),
        ("solutions", solutions_dirs),
    ):
        for d in dirs:
            rel = f"{kind}/{d.name}/index.html"
            html = (d / "index.html").read_text(encoding="utf-8")
            script_hits = len(
                re.findall(r'<script[^>]+src=["\'][^"\']*analytics\.js', html, re.I)
            )
            if script_hits != 1:
                errors.append(f"{rel}: expected 1 analytics.js script, found {script_hits}")
            for banned in (
                "projects-data.js",
                "services-data.js",
                "articles-data.js",
                "content-graph.js",
            ):
                if re.search(
                    rf'<script[^>]+src=["\'][^"\']*{re.escape(banned)}',
                    html,
                    re.I,
                ):
                    errors.append(f"{rel}: must not load {banned}")
            for cta in CTA_RE.findall(html):
                if cta not in ALLOWED_CTAS:
                    errors.append(f"{rel}: unknown data-cta={cta}")
                if "_" in cta:
                    errors.append(f"{rel}: CTA must be kebab-case, got {cta}")
            if kind == "project":
                if 'data-cta="start-project"' not in html:
                    errors.append(f"{rel}: missing start-project CTA")
                if re.search(r'id="project-root"[^>]*\bhidden\b', html):
                    errors.append(f"{rel}: #project-root is hidden")

    # --- SEO quality (warnings preferred; hard errors only for clear breakage) ---
    title_map: dict[str, list[str]] = defaultdict(list)
    desc_map: dict[str, list[str]] = defaultdict(list)
    public_paths: set[str] = set()
    inbound: dict[str, int] = defaultdict(int)

    listing_seeds = {
        "/",
        "/index.html",
        "/projects.html",
        "/services.html",
        "/blog.html",
        "/about.html",
        "/contact.html",
    }
    for seed in listing_seeds:
        inbound[seed] += 1

    for path in ROOT.rglob("*.html"):
        if any(part.startswith(".") for part in path.parts):
            continue
        rel = str(path.relative_to(ROOT)).replace("\\", "/")
        if rel in {"project.html", "service.html", "article.html", "404.html"}:
            continue
        html = path.read_text(encoding="utf-8")
        t = title(html)
        d = meta_desc(html)
        if t:
            title_map[t].append(rel)
        if d:
            desc_map[d].append(rel)

        # path key for inbound graph
        if rel == "index.html":
            key = "/"
        elif rel.endswith("/index.html"):
            key = "/" + rel[: -len("index.html")]
        else:
            key = "/" + rel
        public_paths.add(key)

        for href in HREF_RE.findall(html):
            if href.startswith(("http://", "https://", "mailto:", "tel:")):
                continue
            if href.startswith("#"):
                continue
            clean = href.split("?")[0].split("#")[0]
            if clean.startswith("/"):
                target = clean if clean.endswith("/") or clean.endswith(".html") else clean + "/"
            else:
                # resolve relative against site root when base href=/
                target = "/" + clean.lstrip("./")
            if target.endswith("index.html"):
                target = target[: -len("index.html")]
            if not target.endswith("/") and not target.endswith(".html"):
                target += "/"
            inbound[target] += 1

    for t, files in sorted(title_map.items()):
        if len(files) > 1:
            warnings.append(f"SEO: duplicate title ({len(files)}): {t[:80]} → {', '.join(files[:4])}")
    for d, files in sorted(desc_map.items()):
        if len(files) > 1:
            warnings.append(
                f"SEO: duplicate meta description ({len(files)}): {d[:60]} → {', '.join(files[:4])}"
            )

    # sitemap coverage
    sitemap = ROOT / "sitemap.xml"
    if sitemap.is_file():
        raw_sitemap = sitemap.read_text(encoding="utf-8")
        expected_public = {
            f"{BASE}/",
            f"{BASE}/projects.html",
            f"{BASE}/services.html",
            f"{BASE}/about.html",
            f"{BASE}/blog.html",
            f"{BASE}/contact.html",
        }
        for d in project_dirs:
            expected_public.add(f"{BASE}/project/{d.name}/")
        for d in service_dirs:
            expected_public.add(f"{BASE}/service/{d.name}/")
        for d in article_dirs:
            expected_public.add(f"{BASE}/article/{d.name}/")
        for_root = ROOT / "solutions"
        if for_root.is_dir():
            for d in sorted(for_root.iterdir()):
                if d.is_dir() and (d / "index.html").is_file():
                    expected_public.add(f"{BASE}/solutions/{d.name}/")
        for url in sorted(expected_public):
            if url not in raw_sitemap:
                warnings.append(f"SEO: public page missing from sitemap: {url}")
        if "project.html?slug=" in raw_sitemap or "service.html?slug=" in raw_sitemap:
            errors.append("SEO: sitemap contains legacy query URLs")
    else:
        warnings.append("SEO: sitemap.xml missing")

    # orphan-ish detail pages: listing always counts once; warn if no other inbound
    for kind, dirs in (
        ("project", project_dirs),
        ("service", service_dirs),
        ("article", article_dirs),
        (
            "solutions",
            sorted([d for d in (ROOT / "solutions").iterdir() if d.is_dir()])
            if (ROOT / "solutions").is_dir()
            else [],
        ),
    ):
        for d in dirs:
            key = f"/{kind}/{d.name}/"
            inbound[key] += 1  # listing / service soft-link reachability
            if inbound[key] <= 1:
                warnings.append(f"SEO: {kind}/{d.name} has weak internal inbound links")

    # homepage site-level schema
    home = (ROOT / "index.html").read_text(encoding="utf-8")
    if "WebSite" not in home:
        warnings.append("SEO: index.html missing WebSite JSON-LD")
    if "Organization" not in home:
        warnings.append("SEO: index.html missing Organization JSON-LD")

    robots = ROOT / "robots.txt"
    if robots.is_file():
        rtxt = robots.read_text(encoding="utf-8")
        if "Sitemap:" not in rtxt:
            warnings.append("SEO: robots.txt missing Sitemap directive")
        if "article.html" not in rtxt:
            warnings.append("SEO: robots.txt should Disallow /article.html")
    else:
        warnings.append("SEO: robots.txt missing")

    # Friendly summary
    err_mark = "✓" if not errors else "✗"
    warn_mark = "✓" if not warnings else "⚠"
    print(f"✓ {len(project_dirs)} projects validated")
    print(f"✓ {len(service_dirs)} services validated")
    print(f"✓ {len(article_dirs)} articles validated")
    print(f"✓ {checked} HTML files scanned")
    print(f"{err_mark} {len(errors)} errors / {warn_mark} {len(warnings)} warnings")
    for item in errors[:80]:
        print(f"ERROR: {item}")
    if len(errors) > 80:
        print(f"... {len(errors) - 80} more errors")
    for item in warnings[:40]:
        print(f"WARN: {item}")
    if len(warnings) > 40:
        print(f"... {len(warnings) - 40} more warnings")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
