#!/usr/bin/env python3
"""Lightweight site QA for Hash Studio static pages.

Checks:
  - missing title / meta description / canonical / H1
  - duplicate canonical URLs
  - article/project/service folder integrity
  - article SEO (canonical, OG, JSON-LD, lang/dir)
  - broken internal href targets (basic)
  - images missing width/height attributes (warn)
  - query canonicals

Usage:
  python3 scripts/validate-site.py
  npm run validate
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://hashstudio.ir"

TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
DESC_RE = re.compile(
    r'<meta\s+[^>]*name=["\']description["\'][^>]*content=["\'](.*?)["\']',
    re.I | re.S,
)
DESC_RE2 = re.compile(
    r'<meta\s+[^>]*content=["\'](.*?)["\'][^>]*name=["\']description["\']',
    re.I | re.S,
)
CANON_RE = re.compile(
    r'<link\s+[^>]*rel=["\']canonical["\'][^>]*href=["\'](.*?)["\']',
    re.I | re.S,
)
CANON_RE2 = re.compile(
    r'<link\s+[^>]*href=["\'](.*?)["\'][^>]*rel=["\']canonical["\']',
    re.I | re.S,
)
H1_RE = re.compile(r"<h1\b", re.I)
HREF_RE = re.compile(r'\bhref=["\']([^"\'#]+)["\']', re.I)
IMG_RE = re.compile(r"<img\b[^>]*>", re.I)
WIDTH_RE = re.compile(r"\bwidth=", re.I)
HEIGHT_RE = re.compile(r"\bheight=", re.I)
SLUG_RE = re.compile(r"^[a-z0-9-]+$")
OG_RE = re.compile(r'<meta\s+[^>]*property=["\']og:(title|description|image|url|type)["\']', re.I)
LD_RE = re.compile(r'<script[^>]*type=["\']application/ld\+json["\']', re.I)
LANG_RE = re.compile(r'<html[^>]*\blang=["\']fa["\']', re.I)
DIR_RE = re.compile(r'<html[^>]*\bdir=["\']rtl["\']', re.I)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def meta_desc(html: str) -> str | None:
    m = DESC_RE.search(html) or DESC_RE2.search(html)
    return m.group(1).strip() if m else None


def canonical(html: str) -> str | None:
    m = CANON_RE.search(html) or CANON_RE2.search(html)
    return m.group(1).strip() if m else None


def title(html: str) -> str | None:
    m = TITLE_RE.search(html)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else None


def resolve_href(page: Path, href: str, has_base_root: bool) -> Path | None:
    if href.startswith(("http://", "https://", "mailto:", "tel:", "data:", "javascript:")):
        return None
    href = href.split("?")[0].split("#")[0]
    if not href:
        return None
    if href.startswith("/"):
        target = ROOT / href.lstrip("/")
    elif has_base_root or not href.startswith("."):
        target = ROOT / href
    else:
        target = (page.parent / href).resolve()
        try:
            target.relative_to(ROOT)
        except ValueError:
            return None
    if target.is_dir():
        index = target / "index.html"
        return index if index.exists() else target
    return target


def validate_detail_page(
    rel: str,
    slug: str,
    html: str,
    kind: str,
    errors: list[str],
) -> None:
    expected = f"{BASE}/{kind}/{slug}/"
    c = canonical(html)
    if c != expected:
        errors.append(f"{rel}: canonical expected {expected} got {c}")
    if not LANG_RE.search(html):
        errors.append(f'{rel}: missing lang="fa"')
    if not DIR_RE.search(html):
        errors.append(f'{rel}: missing dir="rtl"')
    if not meta_desc(html):
        errors.append(f"{rel}: missing meta description")
    og_props = {m.group(1).lower() for m in OG_RE.finditer(html)}
    for prop in ("title", "description", "image", "url", "type"):
        if prop not in og_props:
            errors.append(f"{rel}: missing og:{prop}")
    if not LD_RE.search(html):
        errors.append(f"{rel}: missing JSON-LD")
    h1_count = len(H1_RE.findall(html))
    if h1_count != 1:
        errors.append(f"{rel}: expected exactly 1 H1, found {h1_count}")
    for legacy in (
        "article.html?slug=",
        "project.html?slug=",
        "service.html?slug=",
    ):
        if legacy in html:
            errors.append(f"{rel}: contains legacy {legacy} link")
    banner_by_kind = {
        "article": "Generated by scripts/build-content.py",
        "project": "Generated by scripts/build-projects.py",
        "service": "Generated by scripts/build-services.py",
    }
    expected_banner = banner_by_kind.get(kind)
    if expected_banner and expected_banner not in html:
        errors.append(f"{rel}: missing {expected_banner} banner")
    # Primary root must be visible
    if kind == "project" and re.search(r'id="project-root"[^>]*\bhidden\b', html):
        errors.append(f"{rel}: #project-root is hidden")
    if kind == "service" and re.search(r'id="service-root"[^>]*\bhidden\b', html):
        errors.append(f"{rel}: #service-root is hidden")
    # Must not load full datasets on detail pages
    for banned in (
        "projects-data.js",
        "services-data.js",
        "articles-data.js",
        "content-graph.js",
    ):
        if re.search(
            rf'<script[^>]+src=["\'][^"\']*{re.escape(banned)}',
            html,
            re.I,
        ):
            errors.append(f"{rel}: must not load {banned}")
    # Breadcrumb present
    if kind == "project" and "pd-breadcrumb" not in html:
        errors.append(f"{rel}: missing project breadcrumb")
    if kind == "service" and "sd-breadcrumb" not in html:
        errors.append(f"{rel}: missing service breadcrumb")
    if kind == "project" and "CreativeWork" not in html:
        errors.append(f"{rel}: missing CreativeWork JSON-LD")
    if kind == "service" and '"@type":"Service"' not in html.replace(" ", ""):
        errors.append(f"{rel}: missing Service JSON-LD")
    if "BreadcrumbList" not in html:
        errors.append(f"{rel}: missing BreadcrumbList JSON-LD")
    # Body text: require some Persian content beyond chrome
    if len(re.sub(r"\s+", "", html)) < 2000:
        errors.append(f"{rel}: generated HTML looks too thin")

    # Fail empty primary template shells (pre-SSG pattern)
    h1_m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.I | re.S)
    if h1_m and not re.sub(r"<[^>]+>", "", h1_m.group(1)).strip():
        errors.append(f"{rel}: empty H1 (content not statically rendered)")
    for field in ("title", "lead", "name"):
        for m in re.finditer(
            rf"<([a-z0-9]+)[^>]*data-field=\"{field}\"[^>]*>(.*?)</\1>",
            html,
            re.I | re.S,
        ):
            text = re.sub(r"<[^>]+>", "", m.group(2)).strip()
            if not text:
                errors.append(
                    f"{rel}: empty data-field=\"{field}\" (content not statically rendered)"
                )
    if kind == "project":
        if "pd-hero__title" not in html:
            errors.append(f"{rel}: missing project hero title markup")
        if not re.search(r'data-list="toc">\s*<li>', html):
            # TOC may be hidden when <3 sections; allow empty only if toc wrap hidden
            if not re.search(r'data-pd-toc[^>]*\bhidden\b', html) and 'data-pd-toc hidden' not in html:
                if 'pd-toc__link' not in html:
                    errors.append(f"{rel}: project TOC empty but not hidden")
        if "projects-data.js" in html and "<script" in html:
            pass  # already checked via script src
    if kind == "service":
        if "sd-hero__title" not in html and "sd-hero__lead" not in html:
            errors.append(f"{rel}: missing service hero content markup")


def validate_article_page(rel: str, slug: str, html: str, errors: list[str]) -> None:
    validate_detail_page(rel, slug, html, "article", errors)
    if "BlogPosting" not in html and "Article" not in html:
        errors.append(f"{rel}: missing BlogPosting/Article JSON-LD")
    if "article-breadcrumb" not in html and "خانه" not in html:
        errors.append(f"{rel}: missing article breadcrumb")

def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []
    canon_map: dict[str, list[str]] = defaultdict(list)

    project_dirs = [p for p in (ROOT / "project").iterdir() if p.is_dir()]
    service_dirs = [p for p in (ROOT / "service").iterdir() if p.is_dir()]
    article_dirs = (
        [p for p in (ROOT / "article").iterdir() if p.is_dir()]
        if (ROOT / "article").exists()
        else []
    )

    for d in project_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid project slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing project index: project/{d.name}/index.html")

    for d in service_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid service slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing service index: service/{d.name}/index.html")

    for d in article_dirs:
        if not SLUG_RE.match(d.name):
            errors.append(f"invalid article slug folder: {d.name}")
        if not (d / "index.html").exists():
            errors.append(f"missing article index: article/{d.name}/index.html")

    # articles-data.js ↔ article/<slug>/ must match 1:1
    articles_js = (ROOT / "js/articles-data.js").read_text(encoding="utf-8")
    data_article_slugs = set(re.findall(r'^  "([a-z0-9-]+)": \{', articles_js, re.M))
    folder_article_slugs = {d.name for d in article_dirs}
    for slug in sorted(data_article_slugs - folder_article_slugs):
        errors.append(f"articles-data slug missing generated page: article/{slug}/")
    for slug in sorted(folder_article_slugs - data_article_slugs):
        errors.append(f"generated article folder not in articles-data.js: article/{slug}/")

    # projects-data ↔ project folders
    projects_js = (ROOT / "js/projects-data.js").read_text(encoding="utf-8")
    data_project_slugs = set(re.findall(r"^\s+slug:\s*'([a-z0-9-]+)',\s*$", projects_js, re.M))
    folder_project_slugs = {d.name for d in project_dirs}
    for slug in sorted(data_project_slugs - folder_project_slugs):
        errors.append(f"projects-data slug missing page: project/{slug}/")
    for slug in sorted(folder_project_slugs - data_project_slugs):
        errors.append(f"project folder not in projects-data.js: project/{slug}/")

    # services-data ↔ service folders
    services_js = (ROOT / "js/services-data.js").read_text(encoding="utf-8")
    data_service_slugs = set(re.findall(r"^\s+slug:\s*'([a-z0-9-]+)',\s*$", services_js, re.M))
    folder_service_slugs = {d.name for d in service_dirs}
    for slug in sorted(data_service_slugs - folder_service_slugs):
        errors.append(f"services-data slug missing page: service/{slug}/")
    for slug in sorted(folder_service_slugs - data_service_slugs):
        errors.append(f"service folder not in services-data.js: service/{slug}/")

    html_files = sorted(ROOT.rglob("*.html"))
    skip_parts = {"node_modules", ".git"}
    checked = 0

    for path in html_files:
        if any(part in skip_parts for part in path.parts):
            continue
        rel = str(path.relative_to(ROOT))
        html = read(path)
        has_base_root = bool(re.search(r'<base\s+[^>]*href=["\']/["\']', html, re.I))
        checked += 1

        t = title(html)
        if not t:
            errors.append(f"{rel}: missing <title>")

        # Compatibility / legacy shells intentionally thin
        if rel in {"project.html", "service.html", "article.html"}:
            continue

        if rel.startswith("article/") and rel.endswith("/index.html"):
            validate_article_page(rel, path.parent.name, html, errors)
        elif rel.startswith("project/") and rel.endswith("/index.html"):
            validate_detail_page(rel, path.parent.name, html, "project", errors)
        elif rel.startswith("service/") and rel.endswith("/index.html"):
            validate_detail_page(rel, path.parent.name, html, "service", errors)

        d = meta_desc(html)
        if not d and rel != "404.html":
            warnings.append(f"{rel}: missing meta description")

        c = canonical(html)
        if c:
            canon_map[c].append(rel)
            if "project.html?slug=" in c or "service.html?slug=" in c or "article.html?slug=" in c:
                errors.append(f"{rel}: query canonical {c}")
            if "localhost" in c or c.startswith("/"):
                errors.append(f"{rel}: bad canonical {c}")
            if rel.startswith("project/") and "/project/" not in c:
                errors.append(f"{rel}: canonical should be /project/{{slug}}/ → {c}")
            if rel.startswith("service/") and "/service/" not in c:
                errors.append(f"{rel}: canonical should be /service/{{slug}}/ → {c}")
            if rel.startswith("article/") and f"/article/{path.parent.name}/" not in c:
                errors.append(f"{rel}: canonical should be /article/{{slug}}/ → {c}")
        elif rel.endswith("index.html") or rel in {
            "index.html",
            "projects.html",
            "services.html",
            "about.html",
            "contact.html",
            "blog.html",
        }:
            if rel != "404.html":
                warnings.append(f"{rel}: missing canonical")

        if not H1_RE.search(html) and rel != "404.html":
            if 'data-field="name"' not in html and 'data-field="title"' not in html:
                warnings.append(f"{rel}: missing H1")

        for href in HREF_RE.findall(html):
            target = resolve_href(path, href, has_base_root)
            if target is None:
                continue
            if not target.exists():
                pretty = ROOT / href.lstrip("/").rstrip("/").split("?")[0]
                if pretty.is_dir() and (pretty / "index.html").exists():
                    continue
                errors.append(f"{rel}: broken link → {href}")

        for img in IMG_RE.findall(html):
            if "src=" not in img.lower():
                continue
            if not WIDTH_RE.search(img) or not HEIGHT_RE.search(img):
                warnings.append(f"{rel}: img missing width/height")

    for c, files in sorted(canon_map.items()):
        if len(files) > 1:
            errors.append(f"duplicate canonical {c}: {', '.join(files)}")

    # Friendly summary
    err_mark = "✓" if not errors else "✗"
    warn_mark = "✓" if not warnings else "⚠"
    print(f"✓ {len(project_dirs)} projects validated")
    print(f"✓ {len(service_dirs)} services validated")
    print(f"✓ {len(article_dirs)} articles validated")
    print(f"✓ {checked} HTML files scanned")
    print(f"{err_mark} {len(errors)} errors / {warn_mark} {len(warnings)} warnings")
    for item in errors[:80]:
        print(f"ERROR: {item}")
    if len(errors) > 80:
        print(f"... {len(errors) - 80} more errors")
    for item in warnings[:40]:
        print(f"WARN: {item}")
    if len(warnings) > 40:
        print(f"... {len(warnings) - 40} more warnings")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
